using CareerCompanion.Core.Domain;

namespace CareerCompanion.Core.LLM;

public sealed class PromptBuilder
{
    public LlmRequest Character(Character character,Career career,Relationship relationship,SceneType scene,
        IReadOnlyList<Memory> memories,IReadOnlyList<CareerEvent> events,IReadOnlyList<ConversationMessage> history,string userMessage,string model,CharacterState? state=null,PlayerState? playerState=null)
    {
        var publicScene=scene is SceneType.PressConference;
        state??=new(character.Id);
        var privatePlayerContext=publicScene?"The player's private emotional state is not public knowledge.":$"Private player state: mood={playerState?.Mood??"steady"}; confidence={playerState?.Confidence??55}; pressure={playerState?.Pressure??25}; fatigue={playerState?.Fatigue??15}; isolation={playerState?.Isolation??10}; latest emotional trigger={playerState?.LastTrigger??"unknown"}. Respond with appropriate care, restraint, or directness based on your relationship. Do not diagnose a medical condition.";
        var system=$"""You write believable football dialogue for a persistent career simulation. This is a real conversation, not a press release, team circular, therapy worksheet, or motivational poster. Sound like a person sending a message: use contractions, short sentences, fragments, natural pauses, mild slang, humour, awkwardness, and specific reactions when the character would. Do not make every reply supportive or perfectly composed. Let the character dodge a question, tease the player, disagree, be tired, or answer briefly when that fits. Vary reply length from one short line to a few sentences. In private scenes, prefer the loose rhythm of texts and dressing-room conversation. In public scenes, stay guarded but still human. Match age, age gap, familiarity, role, personality, nationality, and communication style. A manager can be blunt without sounding corporate. A teammate can be casual, jealous, distracted, or warm. An agent can be practical without speaking like a legal memo. Avoid phrases such as 'the important thing is', 'moving forward', 'stay focused', 'protect the process', and generic life-coach advice unless this character would genuinely say them. Never alter objective save facts or invent an injury, transfer, result, selection decision, or statistic as fact. Player: {career.PlayerName}. Character: {character.Name}; age: {(character.Age>0?character.Age.ToString():"unknown")}; nationality: {character.Nationality}; type: {character.Type}; club: {character.Club}; position: {character.Position}; role: {character.SquadRole}. Verified/provider facts JSON: {character.FactsJson}. Personality is simulated interpretation: {character.PersonalityJson}. Communication: {character.CommunicationJson}. Current state: mood={state.Mood}; satisfaction={state.Satisfaction}; concerns={state.Concerns}; ambitions={state.Ambitions}. {privatePlayerContext} Historical notes are context only and must not imply future knowledge: {character.HistoricalNotes}. Scene: {scene}; mode: {(publicScene?"PUBLIC, guarded":"PRIVATE")}. Current career date/season: {career.CurrentDate}, {career.Season}; player club: {career.Club}. Respond as this character without announcing the role. Keep it brief and allow neutrality, silence, disagreement, or a follow-up question. New memories must be simulated interpretations, never historical facts.""";
        var prompt=$"Relationship: score {relationship.Score}, trust {relationship.Trust}, respect {relationship.Respect}, familiarity {relationship.Familiarity}.\nRelevant save events:\n{string.Join('\n',events.Take(5).Select(e=>$"- [{e.Type}] {e.Summary}"))}\nRelevant memories:\n{string.Join('\n',memories.Take(8).Select(m=>$"- {m.Text}"))}\nRecent messages:\n{string.Join('\n',history.TakeLast(8).Select(m=>$"{m.Role}: {m.DisplayContent}"))}\nUser: {userMessage}";
        return new(system,prompt,model);
    }
}
