using CareerCompanion.Core.Domain;

namespace CareerCompanion.Core.Services;

/// <summary>
/// Deterministic dialogue for offline play. It is deliberately factual and bounded:
/// it reacts to known career data without inventing results, injuries, or transfers.
/// </summary>
public static class OfflineDialogueLibrary
{
    public static GenerationResult Direct(Character character,Career career,Relationship relationship,CharacterState state,PlayerState player,string message,SceneType scene)
    {
        var text=message.Trim();var lower=text.ToLowerInvariant();var p=character.Profile.Personality;var c=character.Profile.Communication;var seed=Seed(character.Id.ToString(),career.CurrentDate,text,scene.ToString());
        var intent=Intent(lower);var lines=BuildDirectLines(character,career,relationship,state,player,intent,scene,p,c);var dialogue=Pick(lines,seed);var mood=intent switch
        {
            "loss" or "distress"=>"concerned",
            "conflict"=>"guarded",
            "positive"=>"pleased",
            "selection"=>"focused",
            "injury"=>"concerned",
            "transfer" or "international"=>"encouraging",
            _=>state.Mood is "" or "neutral"?"steady":state.Mood
        };
        var relationshipDelta=intent switch{"positive"=>1,"loss" or "distress"=>p.Openness>=55?1:0,"conflict"=>p.Diplomacy>=65?0:-1,"selection"=>p.Loyalty>=60?1:0,_=>0};
        var trustDelta=intent is "loss" or "distress"?1:intent=="conflict"?-1:0;var respectDelta=intent is "selection" or "training"&&p.Professionalism>=65?1:0;
        var memory=intent switch{"loss" or "distress"=>$"Discussed the difficult moment: {Trim(text,100)}","selection"=>$"Discussed selection and playing time: {Trim(text,100)}","transfer"=>$"Discussed the career move: {Trim(text,100)}","international"=>$"Discussed international duty: {Trim(text,100)}",_=>null};
        return new(dialogue,mood,relationshipDelta,trustDelta,respectDelta,memory is null?Array.Empty<string>():new[]{memory},0,0,"offline-library");
    }

    public static string MatchReaction(Character character,Career career,CareerMatch match,CareerEvent evt)
    {
        var input=match.Input;var p=character.Profile.Personality;var c=character.Profile.Communication;var playful=p.Humor>=58||c.Humor>=58;var direct=p.Diplomacy<45||c.Directness>=74;var seed=Seed(character.Id.ToString(),career.CurrentDate,evt.Id.ToString(),evt.Type);
        if(character.Type==CharacterType.Manager)
        {
            if(input.TeamContext=="International")return input.TeamScore>input.OpponentScore?Pick(new[]{$"Good work with {input.RepresentingTeam}. Recover properly, then return ready for club duty.","That is a useful result for {input.RepresentingTeam}. Enjoy it, then turn your attention back to the club.","You represented {input.RepresentingTeam} well. Manage your recovery because the club schedule will not wait."},seed):Pick(new[]{$"International defeats hurt. Reset tonight and bring your focus back to the club.","A difficult night for {input.RepresentingTeam}. Learn from it, recover, and return ready.","That result will sting, but international duty is part of your growth. We will discuss it when you are back."},seed);
            return evt.Type switch
            {
                "PLAYER_RED_CARD"=>Pick(direct?new[]{"The sending-off put the team in trouble. I need better discipline from you.","You cannot help us from the tunnel. We will discuss the decision, but we must start with your responsibility.","That was avoidable. Make sure one mistake does not become a pattern."}:new[]{"We will review the sending-off together. Your response now matters more than the mistake.","The red card changed the match. Come in tomorrow and we will work through what happened.","I know the moment got away from you. Show me maturity in how you respond."},seed),
                "PLAYER_HATTRICK"=>Pick(p.Professionalism>=70?new[]{"Excellent finishing. Enjoy the achievement, then set the standard again in training.","Three goals is a serious contribution. The challenge is making this level normal for you.","That was clinical. Recover properly and keep the hunger that produced it."}:new[]{"Three goals is a fine way to make your case. Now show me you can repeat it.","You took your chances well today. Now we see how you handle the attention.","A special afternoon. Do not let praise replace the work that got you here."},seed),
                "PLAYER_BRACE"=>Pick(new[]{"Two goals and a disciplined performance. That is the level we need from you.","You changed the match with your finishing. Keep asking for that responsibility.","A strong contribution today. The next step is to repeat it when the game is less comfortable."},seed),
                "LARGE_DEFEAT"=>Pick(direct?new[]{"That result was below our standard. We work tomorrow and respond next match.","We were second best and there is no point hiding from it. The response starts in training.","That performance was not acceptable. I expect character from the group now."}:new[]{"That result is difficult to accept. We will find the response together.","The scoreline does not tell the whole story, but it tells us enough. We need to improve quickly.","A hard defeat, but we have a chance to answer it. Stay together and stay honest."},seed),
                "PLAYER_BENCHED"=>Pick(p.Patience>=60?new[]{"Keep working. Your opportunity will come if your training stays at the right level.","Selection is a moving conversation. Make your daily work impossible to ignore.","Stay ready. Matches are often changed by the players who prepare properly on the bench."}:new[]{"You made an impact from the bench. Make selection impossible to ignore next time.","I need more urgency from you in training if you want to start the next one.","Use the disappointment. Turn it into better work this week."},seed),
                "PENALTY_MISSED"=>Pick(new[]{"Missing hurts, but the next penalty is not decided by this one. Keep taking responsibility.","We will review the moment, then we move on. I trust players who are willing to take the ball.","You cannot change the miss. You can decide how you train tomorrow."},seed),
                "PLAYER_INJURED"=>Pick(new[]{"Your recovery comes first. We will not rush you back for one match.","Stay patient with the medical plan and keep communicating with the staff.","Football will still be here when you are ready. Focus on the steps in front of you."},seed),
                _=>input.TeamScore>input.OpponentScore?Pick(playful?new[]{"Good result. Enjoy it briefly, then we move on to the next job.","A useful win. Celebrate with the group, then recover properly.","Three points and a clean response. Now we protect the momentum."}:new[]{"Good result. Stay focused because the next match arrives quickly.","A professional result. Take the confidence into the next session.","That is the standard we need. Recover and prepare for the next challenge."},seed):input.TeamScore<input.OpponentScore?Pick(direct?new[]{"Review that performance honestly. We need a stronger response next time.","We did not do enough. Be ready for a demanding training session.","The result is on all of us, but each player must own their part."}:new[]{"We need to learn from that performance and prepare a stronger response.","It was a difficult result. We will look at the details without losing perspective.","We will regroup. Keep your head up and stay connected to the group."},seed):Pick(new[]{"A point, but there was more available to us today.","The draw keeps us moving, though we need to be sharper in the important moments.","Not the result we wanted, but there are useful lessons in the performance."},seed)
            };
        }
        if(input.TeamContext=="International")return input.TeamScore>input.OpponentScore?Pick(new[]{$"That win with {input.RepresentingTeam} means a lot. Enjoy the night.","You will remember that result for a long time. Well done with {input.RepresentingTeam}.","A big night for you and {input.RepresentingTeam}. Make sure you enjoy it before the next job."},seed):Pick(new[]{$"Tough result with {input.RepresentingTeam}. We will pick you up when you get back.","That one will hurt, but you gave everything for {input.RepresentingTeam}. Keep your head up.","International defeats feel different. Talk to the lads when you are ready, then come home focused."},seed);
        return evt.Type switch
        {
            "PLAYER_HATTRICK"=>Pick(playful?new[]{$"Unreal, {career.PlayerName}. You were unplayable. Save one for me next time.","Three goals? Leave some records for the rest of us.","I was going to congratulate you, but I am still trying to catch my breath."}:new[]{"That was a top-class finishing display. You earned every bit of it.","You took every chance with real conviction. That is a performance to remember.","A brilliant afternoon. The movement, timing, and finishing were all there."},seed),
            "PLAYER_BRACE"=>Pick(new[]{"Two goals and you still did the work without the ball. That was a proper performance.","You made the difference today. Keep that confidence for the next one.","A brace is nice, but the way you stayed involved was even better."},seed),
            "PLAYER_RED_CARD"=>Pick(direct?new[]{"That red card left us chasing the game. We need you on the pitch.","You let the moment beat you. We need a calmer version of you next time.","The team needed you and lost you. Own it, then make amends."}:new[]{"Forget the noise around the sending-off. We need you back with us.","That was a hard moment. We know you are better than one decision.","Do not disappear after the mistake. Come back into the group."},seed),
            "PENALTY_MISSED"=>Pick(new[]{"It happens. The brave part was taking it in the first place.","That miss will replay in your head, but it does not erase the rest of your game.","Next time you take the ball again. That is how you answer it."},seed),
            "PLAYER_INJURED"=>Pick(new[]{"Forget the match for now. Get yourself right and we will see you when you are ready.","That looked painful. Message me after the medical check, yeah?","No pressure to reply. Just focus on recovering properly."},seed),
            "LARGE_DEFEAT"=>Pick(p.Loyalty>=65?new[]{"Tough one. We stay together and put it right next match.","Nobody is walking away from this group. We answer it together.","That hurt, but I know the lads will show up for the response."}:new[]{"That hurt. We cannot hide from it, but we can answer on the pitch.","We were miles off it today. We owe the supporters a reaction.","Do not pretend it was fine. Then do not let it become the next match too."},seed),
            "LATE_WINNER"=>Pick(playful?new[]{"I still cannot believe that finish. The dressing room nearly lost its roof.","You waited until the last possible second to make us all panic.","That finish was ridiculous. I am claiming I called it before you shot."}:new[]{"That finish changed everything. What a moment.","You showed nerve when the match was slipping away. Brilliant timing.","The late winner says a lot about your belief. Hold on to that feeling."},seed),
            _=>input.TeamScore>input.OpponentScore?Pick(playful?new[]{"Big result. I am claiming an assist for the celebration.","Three points, no complaints. Food is on you if you keep scoring.","That was fun. Let us make a habit of winning without the drama next time."}:new[]{"Big result today. You were important to it.","A proper team performance and a valuable win.","Good work today. Recover well and keep the confidence moving."},seed):input.TeamScore<input.OpponentScore?Pick(p.Openness>=55?new[]{"That one hurts. Talk to me if you need to clear your head.","I know you are disappointed. Come around later if you do not want to be alone.","It was a bad day, not the end of the story. Stay close to the group."}:new[]{"We have to respond. No hiding from this one.","We were not good enough. We need to be better next time.","That is football, but it still hurts. We go again."},seed):Pick(new[]{"A point. Feels like we left something out there.","Not a defeat, not enough of a win. We can be honest about both.","The draw keeps us moving, but I think we had more in us today."},seed)
        };
    }

    public static string PreMatch(Character character,CareerFixture fixture,bool rival,string? keyThreat,int seed)
    {
        var p=character.Profile.Personality;var c=character.Profile.Communication;var opponent=fixture.Opponent;var venue=fixture.IsHome?"at home":$"away at {opponent}";
        if(character.Type==CharacterType.Manager)return Pick(rival?new[]{$"This is {opponent}, {venue}, and they will make it emotional. Be disciplined before you try to win it.",$"Rivalry matches punish loose decisions. Start with our shape against {opponent}, then let your quality decide it.",$"The occasion will be loud against {opponent}. I need your head clear and your work rate high."}:new[]{$"Against {opponent}, our first job is to control the spaces and play with patience.",$"Prepare properly for {opponent}. The details in your role will matter more than the noise around the match.",$"We have a plan for {opponent}. Trust it, communicate, and be ready for the moments that change the game."},seed);
        if(rival)return Pick(p.Humor>=60?new[]{$"Big one against {opponent}. If the atmosphere gets wild, at least make sure we enjoy winning it.",$"They will be talking before kick-off. Let us give them something to talk about after it.",$"Rivalry day. Keep your head, win your battles, and do not give them an easy story."}:new[]{$"Big one against {opponent}. We need to set the tone early.",$"The atmosphere will be intense. Stay brave on the ball and stay together.",$"Matches like this are remembered. Let us make sure the memory belongs to us."},seed);
        return Pick(new[]{$"Ready for {opponent}? Let us start quickly and make the match ours.",$"We have a chance to set the rhythm against {opponent}. Stay switched on from the first whistle.",$"No need for a speech. Do your job, help the man beside you, and the match will open up.",$"I have been looking forward to this one. Bring your sharpness and I will bring mine."},seed);
    }

    public static string Support(Character person,int severity,string opponent,int seed)
    {
        var p=person.Profile.Personality;var direct=person.Profile.Communication.Directness>=70;var high=severity>=22;
        if(person.Type==CharacterType.Agent)return Pick(high?new[]{$"I heard how badly the result against {opponent} hit you. Do not sit with this alone tonight.",$"I heard how badly the result against {opponent} hit you. Do not sit with this alone. Call me when you are somewhere quiet.",$"Do not sit with this alone. I am checking in because this is exactly when you need people around you. No performance, just talk to me."}:new[]{$"Forget the noise around the result for a moment. Call me when you are somewhere quiet.",$"Keep tonight simple: eat, rest, and let me know how your head feels tomorrow.",$"You have a career to manage, but you are also allowed to have a difficult evening. I am here."},seed);
        if(person.Type==CharacterType.Manager)return Pick(high?new[]{$"Football can wait tonight. Speak to someone you trust and check in with me tomorrow.",$"I know the result has landed heavily. Take the evening away from the noise, then we will make a plan.",$"You are still part of this group. Rest first, then we will decide what support you need."}:new[]{$"I know this result hurts. Take tonight, clear your head, and we will talk properly tomorrow.",$"Do not let one performance become a judgement on your whole season. We will review it calmly.",$"You can be disappointed and still be ready to respond. We will help you get there."},seed);
        return Pick(high?new[]{$"I know this one has hit you hard. You do not need to find the right words.",$"Come sit with us for a while. You do not have to talk about the match.",$"I am not going to tell you to cheer up. I am just here, and I am not going anywhere."}:new[]{$"That result is still hurting, I know. If you want company, call me.",$"Bad days happen. Stay near the lads tonight and do not disappear.",$"You do not have to pretend it was fine. We can talk when you are ready."},seed);
    }

    public static string Transfer(Character agent,string from,string to,int seed)=>Pick(new[]{$"The move from {from} to {to} is complete. Settle quickly, learn the environment, and make the first opportunity count.",$"A new club means a new test. Be patient with the adjustment from {from} to {to}, but do not hide from the competition.",$"The transfer is done. Your first target at {to} is simple: earn trust every day and let the football follow.",$"Forget the announcement now. The real work starts at {to}, and I will help you manage the noise around it."},seed);
    public static string Record(Character agent,string summary,int seed)=>Pick(new[]{$"That is not just a good performance. You have put your name into the record book. Take the moment in, then protect the standard you have set.",$"Records are built from thousands of ordinary decisions before the special day. Enjoy this one, then keep the habits that created it.",$"Your name is now attached to a piece of football history. Let yourself feel that, but do not let the attention change your work.",$"That achievement will travel with you. The next challenge is proving it was the beginning of a level, not a single afternoon."},seed);
    public static string International(Character agent,string team,bool debut,int seed)=>debut?Pick(new[]{$"A senior debut for {team} is a real career milestone. Take it in, then keep building on it.",$"Your first cap changes how people see your career. Enjoy the pride, then return to the daily work.",$"You have crossed an important line with {team}. Keep your feet on the ground and make the next selection inevitable."},seed):Pick(new[]{$"Another cap for {team}. International matches raise your profile, but your next club performance still matters.",$"You are becoming a regular part of {team}. Manage the travel and keep your club standards high.",$"Every appearance for {team} adds experience. Bring that confidence back to the club without losing your balance."},seed);
    public static string SquadArrival(Character player,int seed)=>Pick(new[]{$"Good to meet you. I am settling in and looking forward to playing together.",$"Welcome in. I have heard good things, but I would rather see what you are like around the group.",$"New club, new faces. If you need anything while you settle, come find me.",$"Welcome. The first few weeks are always strange, so do not be afraid to ask where everything is.",$"Good to have you here. Let us make the adjustment easier for each other."},seed);
    public static string Statement(Character character,bool teamFirst,bool blame,bool referee,bool accountable,int seed)
    {
        if(character.Type==CharacterType.Manager)return blame?Pick(new[]{"We discuss problems inside the dressing room, not through the press. Keep that in mind.","If there is an issue, bring it to me directly. Public blame will not improve the team.","You are entitled to your view, but the group needs responsibility more than accusations."},seed):referee?Pick(new[]{"Do not let comments about officials become a distraction. Focus on what we control.","The decision can be debated, but the next performance cannot be.","Leave the referee discussion there. Your energy is needed on the football."},seed):accountable?Pick(new[]{"Taking responsibility was the right response. Now show it in the next performance.","Words matter, but the best answer will come in training and the next match.","That was mature. Keep the ownership when the work becomes difficult."},seed):"The team will judge the statement by what happens next.";
        if(teamFirst)return Pick(new[]{"The squad appreciated you putting the team first in there. We stay together.","Good answer. Nobody wins alone, and the lads noticed you said it.","That is the kind of message that keeps a dressing room connected."},seed);
        if(blame||referee)return Pick(new[]{"Some of the lads noticed those comments. Better to settle it face to face in the dressing room.","The headlines will move on, but the people in the room will remember how it felt.","Come speak to us directly. It is easier to fix tension when nobody is performing for cameras."},seed);
        return accountable?Pick(new[]{"Fair answer. We can respect someone who owns their part.","That sounded honest. Now let us turn it into something useful.","The supporters will appreciate the honesty if the next performance follows it."},seed):"I saw the interview. We will see how the next match feels.";
    }

    private static IReadOnlyList<string> BuildDirectLines(Character character,Career career,Relationship relationship,CharacterState state,PlayerState player,string intent,SceneType scene,Personality p,CommunicationStyle c)
    {
        var name=career.PlayerName;var friendly=relationship.Friendliness+relationship.Familiarity>70;var tense=relationship.Tension+relationship.Rivalry>60;var manager=character.Type==CharacterType.Manager;var agent=character.Type==CharacterType.Agent;var privateScene=scene is SceneType.PrivateMessage or SceneType.ManagerOffice or SceneType.TransferDiscussion;
        return intent switch
        {
            "greeting"=>manager?new[]{"Morning. How is your head today?","Good to hear from you. Are you ready for the work ahead?","Morning. Give me an honest read on how you are feeling.","Hello. I have a few minutes before training if you want to talk.","Good morning. We can keep this brief or take the time it needs."}:agent?new[]{"Hello. I was going to check in with you anyway.","Good to hear from you. What do you need from me today?","I am here. Is this about football, or is it about everything around football?","Morning. I have been keeping an eye on how things are developing.","Hello. Talk to me, and start wherever makes sense."}:new[]{"Hey. How are you holding up?","Good to hear from you. What is going on?","I was about to message you. You all right?","Hey. Give me the version you would not say in the changing room.","Hello. I am around if you need a proper conversation."},
            "loss" or "distress"=>manager?new[]{"I know the result has stayed with you. We will separate the emotion from the work and deal with both.","You do not need to apologise for caring. We need you recovered enough to think clearly.","I have seen players mistake a bad result for a bad identity. Do not make that mistake.","Take the evening seriously, but do not let it become a verdict on your career.","You are allowed to be upset. Tomorrow, we turn that feeling into something useful."}:agent?new[]{"Let us keep the noise away from you tonight. I can handle calls and speculation while you reset.","The result is painful, but it does not change the opportunities in front of you.","Tell me whether you want advice, silence, or someone to take the pressure off for a few hours.","I know the football matters deeply to you. That is exactly why we need to protect your head now.","We can review the match later. Tonight, you are more important than the headlines."}:new[]{"I am here. You do not have to make the feeling smaller for me.","Come find me after dinner. We can talk about the match, or absolutely nothing.","You can be disappointed without disappearing from everyone who cares about you.","That result is one night. I know it does not feel like one night right now, but it is.","No motivational speech from me. Just company, if you want it."},
            "positive"=>manager?new[]{"Good. Keep that confidence quiet enough to work and strong enough to show.","Enjoy the result, then protect it with the next training session.","You played with conviction. Now make that feeling repeatable.","The group felt your energy today. Use it well rather than chasing praise.","A good day. Recover properly and arrive hungry for the next one."}:new[]{"That was a good feeling, was it not?","You earned the smile. I am still replaying the best moment.","Good days make the hard ones worth it. Keep that energy close.","I knew you had that performance in you. I am glad everyone else saw it too.","Enjoy tonight. Tomorrow we can start talking about doing it again."},
            "selection"=>manager?new[]{"Selection is a conversation between your daily work and the needs of the match.","I have not closed any door. Give me a reason to choose you again.","If you want more minutes, show me more reasons to trust you with them.","I understand the frustration. Bring it to training, where it can help you.","You are part of the plan, but your next step is still yours to earn."}:new[]{"I know you want to start. Keep pushing, and do not let the disappointment isolate you.","You looked ready when you came on. That matters more than sulking about the bench.","Your chance will come. When it does, make it difficult for anyone to leave you out.","I would be frustrated too. Just do not let it turn into bad work.","The squad notices who stays ready. Keep showing that you are one of them."},
            "training"=>manager?new[]{"Training is where selection starts. Give me intensity and clarity today.","The details are improving. Keep the standard when nobody is applauding.","I want you to be brave with the ball and reliable without it.","One sharp session will not decide your career, but a month of them can change it.","Come early, prepare properly, and make the work visible."}:new[]{"Training was sharp today. You looked switched on from the first drill.","Stay after for ten minutes if you want to work on that movement.","The work nobody sees usually decides the moments everyone remembers.","I can see you are building something. Do not rush the result.","Good session. Eat, recover, and do not waste the work you put in."},
            "injury"=>agent?new[]{"I will deal with the practical side. You focus on the recovery plan and keep me updated.","Do not let impatience turn a short absence into a longer one.","The medical timeline is the fact. Everything else is noise until we know more.","We can manage the questions from outside. You only need to manage the next recovery step.","Your value has not changed because you are unavailable for a while."}:manager?new[]{"The medical team will guide the return. I will not let outside pressure rush you.","Stay involved with the group while you recover, but respect the work your body needs.","You are still part of the team every day, even when you cannot play.","We will miss you on the pitch. That is not a reason to take a shortcut back.","Focus on what you can control today, not the date you wish you could return."}:new[]{"How are you feeling after the check?","Come around if you are bored. I can bring terrible food and better company.","Do not rush it for us. We want you back properly.","You are still one of us, even if you are watching from the side for now.","Message me after rehab. I want to know how it really feels, not just what the report says."},
            "transfer"=>agent?new[]{"A move is exciting, but the first month is about listening, learning, and earning trust.","Do not compare every new room with the old one. Build your place here.","The announcement is the easy part. The daily adjustment is where the move becomes real.","I will handle the external noise. You focus on the football and the people beside you.","New club, same standards. That is how you make the transition yours."}:new[]{"So it is really happening. Strange feeling, is it not?","Whatever comes next, do not forget the people who helped you get here.","New colours will take some getting used to. I hope they treat you well.","I am proud of you, even if I am selfishly sorry to see you leave.","The next chapter is yours. Make sure you keep the parts of yourself that got you here."},
            "international"=>new[]{"That call-up must feel different from a club selection.","Bring the confidence back with you when international duty is over.","Your family must be proud. Let yourself enjoy that part of it.","The shirt carries history, but you still have to play your own game in it.","Travel well, represent yourself properly, and come back healthy."},
            "conflict"=>tense?new[]{"I do not want this to become a performance for everyone else.","Say what you mean to me directly and we can work with it.","We clearly see the moment differently. I am willing to hear your side.","I am not going to pretend there is no tension. Let us decide what to do with it.","The team cannot carry an argument forever. We need a way forward."}:new[]{"I do not want a small misunderstanding to become a bigger story.","If I upset you, tell me what I missed.","We can disagree without making the room uncomfortable for everyone.","I would rather clear the air now than let it sit between us.","Give me the honest version. I will try not to answer defensively."},
            "support"=>new[]{"You can say it plainly. I am not going to judge the first version.","Do you want advice, distraction, or just someone to stay on the phone?","You do not have to be useful in this conversation.","I have time. Start with the part you keep replaying.","Whatever you are carrying, you do not need to carry all of it alone."},
            "question"=>manager?new[]{"That is a fair question. Let us look at what we know before we decide what it means.","I will give you an honest answer, but I want an honest conversation in return.","Come to my office before training and we will work through it properly.","The short answer is not enough here. Tell me what is really worrying you.","I understand why you are asking. We can discuss the football and the feeling behind it."}:new[]{"You want the honest version? I will give it to you.","I have wondered about that too. Let us not rush the answer.","Tell me what made you ask, and I will tell you what I think.","That is a bigger question than it looks. We have time.","I hear you. Give me the context and I will not guess at the rest."},
            _=>manager?new[]{"Understood. Keep your focus on the next session and bring that standard with you.","I hear you. We will turn it into a practical next step.","Noted. We deal with the important part first, then move on.","Thanks for telling me. I will keep it in mind when we plan the next session.","Stay close to the work. It has a way of making the next decision clearer."}:friendly?new[]{"I get you. Keep talking if there is more behind it.","Fair enough. I am glad you said it instead of keeping it to yourself.","That makes sense to me. We will figure out the next bit together.","I hear you. Let us not make it heavier than it needs to be.","Thanks for trusting me with that."}:new[]{"I am listening. Tell me what is on your mind.","I get it. Say as much or as little as you want.","Understood. We can leave it there or keep talking.","That is worth thinking about. I will not dismiss it.","I hear you. Let us take it one piece at a time."}
        };
    }

    private static string Intent(string text)
    {
        if(Contains(text,"depress","suicid","cannot cope","not okay","not ok","alone","cry","empty","worthless","anxious"))return "distress";
        if(Contains(text,"lose","lost","defeat","bad result","hurt","awful","terrible","angry"))return "loss";
        if(Contains(text,"injur","pain","physio","rehab","medical","ankle","knee","hamstring"))return "injury";
        if(Contains(text,"transfer","move","new club","leaving","leave us"))return "transfer";
        if(Contains(text,"country","national team","international","call-up","call up","cap","world cup","euro"))return "international";
        if(Contains(text,"bench","benched","start","starting","minutes","selection","picked","lineup","line-up"))return "selection";
        if(Contains(text,"training","session","drill","work out","workout","practice"))return "training";
        if(Contains(text,"argue","argument","angry with","upset with","disagree","blame","problem with"))return "conflict";
        if(Contains(text,"help","support","advice","talk","lonely","listen"))return "support";
        if(Contains(text,"hello","hi ","hey","morning","evening","yo "))return "greeting";
        if(Contains(text,"thank","thanks","proud","win","won","good","great","brilliant","happy"))return "positive";
        if(text.Contains('?')||text.StartsWith("how ",StringComparison.OrdinalIgnoreCase)||text.StartsWith("what ",StringComparison.OrdinalIgnoreCase)||text.StartsWith("why ",StringComparison.OrdinalIgnoreCase))return "question";
        return "general";
    }
    private static bool Contains(string text,params string[] terms)=>terms.Any(term=>text.Contains(term,StringComparison.OrdinalIgnoreCase));
    private static string Pick(IReadOnlyList<string> values,int seed)=>values.Count==0?"I am here.":values[Math.Abs(seed)%values.Count];
    private static int Seed(params string[] values){unchecked{var hash=17;foreach(var value in values){foreach(var ch in value)hash=hash*31+ch;hash=hash*31+1;}return hash&int.MaxValue;}}
    private static string Trim(string value,int length)=>value.Length<=length?value:value[..length]+"...";
}
