using CareerCompanion.Core.Domain;
using CareerCompanion.Core.LLM;
using CareerCompanion.Core.Persistence;
using CareerCompanion.Core.Services;
using CareerCompanion.Core.Providers.Fifa18;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Net.Http;
using System.IO;

namespace CareerCompanion.App;

public sealed class MainViewModel : INotifyPropertyChanged
{
    private readonly Database _db; private readonly CareerService _careers; private Character? _selectedCharacter; private SquadMemberView? _selectedSquadMember; private MatchReviewView? _selectedMatchReview; private CareerNotification? _selectedNotification; private CareerMatch? _selectedLoggedMatch; private long? _editingMatchId; private long? _loadedReviewId; private Fifa18ParsedCareer? _loadedReviewSnapshot; private PostMatchInterview? _activeInterview; private PostMatchInterview? _latestInterview; private Career? _currentCareer; private Fifa18ParsedCareer? _pendingFifa; private bool _automaticGenerationBusy;
    public ObservableCollection<Career> Careers {get;}=[]; public ObservableCollection<Character> Characters{get;}=[];public ObservableCollection<SquadMemberView> SquadMembers{get;}=[];public ObservableCollection<SquadMemberView> FormerTeammates{get;}=[];public ObservableCollection<Character> OtherCharacters{get;}=[];public ObservableCollection<CareerMatch> MatchHistory{get;}=[];public ObservableCollection<MatchReviewView> PendingMatchReviews{get;}=[];public ObservableCollection<CareerNotification> Notifications{get;}=[];public ObservableCollection<CareerProgressSnapshot> ProgressSnapshots{get;}=[];public ObservableCollection<string> InterviewTranscript{get;}=[];public ObservableCollection<CareerFixture> Fixtures{get;}=[];public ObservableCollection<CareerEvent> Events{get;}=[];public ObservableCollection<NewsItem> News{get;}=[];public ObservableCollection<SocialPost> Social{get;}=[];public ObservableCollection<ConversationMessage> Messages{get;}=[];public ObservableCollection<string> DashboardItems{get;}=[];
    public IReadOnlyList<string> CharacterTypes{get;}=Enum.GetNames<CharacterType>();public IReadOnlyList<string> SceneTypes{get;}=Enum.GetNames<SceneType>();
    public IReadOnlyList<string> SquadFilters{get;}=["All","Goalkeepers","Defenders","Midfielders","Forwards","Injured"];
    public event PropertyChangedEventHandler? PropertyChanged;
    public MainViewModel(Database db){_db=db;_careers=new(db);LoadSettings();FifaSettingsDirectory=new Fifa18SaveLocator().FindSettingsDirectory()??"FIFA 18 settings directory not found";ReloadCareers();CurrentCareer=Careers.FirstOrDefault();MatchDate=CurrentCareer?.CurrentDate??DateTime.Today.ToString("yyyy-MM-dd");}
    private void OnChanged([CallerMemberName]string? name=null)=>PropertyChanged?.Invoke(this,new(name));
    private bool Set<T>(ref T field,T value,[CallerMemberName]string? name=null){if(EqualityComparer<T>.Default.Equals(field,value))return false;field=value;OnChanged(name);return true;}
    public Career? CurrentCareer{get=>_currentCareer;set{if(Set(ref _currentCareer,value)){Refresh();OnChanged(nameof(NoCareerVisibility));}}}
    public Character? SelectedCharacter{get=>_selectedCharacter;set{if(Set(ref _selectedCharacter,value)){LoadMessages();OnChanged(nameof(SelectedCharacterSummary));OnChanged(nameof(SelectedRelationship));}}}
    public SquadMemberView? SelectedSquadMember{get=>_selectedSquadMember;set{if(Set(ref _selectedSquadMember,value)){if(value is not null)SelectedCharacter=value.Character;OnChanged(nameof(SelectedSquadFacts));OnChanged(nameof(SelectedSquadRelationship));}}}
    public MatchReviewView? SelectedMatchReview{get=>_selectedMatchReview;set{if(Set(ref _selectedMatchReview,value)){if(_loadedReviewId is not null&&_loadedReviewId!=value?.Id){_loadedReviewId=null;_loadedReviewSnapshot=null;}OnChanged(nameof(SelectedReviewDetails));}}}
    public CareerNotification? SelectedNotification{get=>_selectedNotification;set=>Set(ref _selectedNotification,value);}
    public CareerMatch? SelectedLoggedMatch{get=>_selectedLoggedMatch;set{if(Set(ref _selectedLoggedMatch,value))OnChanged(nameof(SelectedMatchHistoryDetails));}}
    string _selectedSquadFilter="All";public string SelectedSquadFilter{get=>_selectedSquadFilter;set{if(Set(ref _selectedSquadFilter,value))RebuildSquadViews();}}
    public Visibility NoCareerVisibility=>CurrentCareer is null?Visibility.Visible:Visibility.Collapsed;
    public string PlayerSummary=>CurrentCareer is null?"":$"#{CurrentCareer.ShirtNumber} | {CurrentCareer.Position} | {CurrentCareer.Nationality}";
    public string RecentMatchSummary{get;private set;}="No matches logged";public string CurrentForm{get;private set;}="No form";public string NextFixture{get{if(CurrentCareer is null)return"Not available";var fixture=_db.GetFixtures(CurrentCareer.Id).FirstOrDefault(x=>x.Status=="Upcoming");return fixture is null?_db.GetSetting($"career:{CurrentCareer.Id}:next")??CurrentCareer.NextOpponent??"Not entered":$"{fixture.Date} | {(fixture.IsHome?"vs":"at")} {fixture.Opponent} | {fixture.Competition}";}}
    public string SelectedCharacterSummary=>SelectedCharacter is null?"Select a character":$"{SelectedCharacter.Type} | {(SelectedCharacter.Age>0?SelectedCharacter.Age.ToString():"Age unknown")} | {SelectedCharacter.Nationality}\n{SelectedCharacter.Position} | {SelectedCharacter.SquadRole}";
    public string SelectedRelationship{get{if(SelectedCharacter is null)return"";var r=_db.GetRelationship(SelectedCharacter.Id);return $"Relationship {Label(r.Score)} | Trust {Label(r.Trust)} | Respect {Label(r.Respect)}";}}
    public string SelectedSquadRelationship{get{if(SelectedSquadMember is null)return"";var r=_db.GetRelationship(SelectedSquadMember.Id);return $"Relationship {Label(r.Score)} | Trust {Label(r.Trust)} | Respect {Label(r.Respect)}";}}
    private static string Label(int n)=>n switch{>=60=>"very strong",>=25=>"positive",<=-60=>"hostile",<=-25=>"strained",_=>"neutral"};
    public string SelectedSquadFacts=>SelectedSquadMember is null?"Select a player to inspect their save data.":$"{SelectedSquadMember.ShirtLabel} | {SelectedSquadMember.Position} | {SelectedSquadMember.OverallLabel}\n{SelectedSquadMember.FormLabel} | {SelectedSquadMember.Availability}\n{SelectedSquadMember.Age} years old | {SelectedSquadMember.Nationality} | {SelectedSquadMember.SourceLabel}";
    private CareerFixture? UpcomingFixture=>Fixtures.FirstOrDefault(x=>x.Status=="Upcoming");
    public string PreMatchOpponent=>UpcomingFixture is null?"No upcoming fixture detected":UpcomingFixture.Opponent;
    public string PreMatchMeta=>UpcomingFixture is null?"Play or save before a fixture in FIFA 18 to update this briefing.":$"{UpcomingFixture.Date} | {(UpcomingFixture.IsHome?"HOME":"AWAY")} | {UpcomingFixture.Competition}";
    public string PreMatchForm=>CurrentForm;
    public string PreMatchAvailability{get{var active=SquadMembers.Count;var injured=SquadMembers.Count(x=>x.Injured);return active==0?"Squad data unavailable":injured==0?$"{active} squad players | suspension data limited":$"{injured} injury flags | suspension data limited";}}
    public string PreMatchKeyPlayers{get{var players=SquadMembers.Where(x=>x.Overall is not null).OrderByDescending(x=>x.Overall).Take(3).Select(x=>$"{x.Name} ({x.Position}, {x.Overall})").ToList();return players.Count==0?"No player ratings detected":string.Join(" | ",players);}}
    public string PreMatchIntel=>UpcomingFixture is null?"No FIFA preview has been detected yet.":UpcomingFixture.Evidence;
    public string PreMatchScouting{get{if(CurrentCareer is null)return"No opponent scouting is available.";var json=_db.GetSetting($"career:{CurrentCareer.Id}:opponent_scout");if(string.IsNullOrWhiteSpace(json))return"No verified opponent squad snapshot is available.";try{var scout=JsonSerializer.Deserialize<Fifa18OpponentScout>(json);if(scout is null)return"No verified opponent squad snapshot is available.";var parts=new List<string>();if(!string.IsNullOrWhiteSpace(scout.ManagerName))parts.Add("Manager: "+scout.ManagerName);if(!string.IsNullOrWhiteSpace(scout.StadiumName))parts.Add("Stadium: "+scout.StadiumName);if(scout.IsRival)parts.Add("FIFA listed rivalry");if(scout.KeyPlayers.Count>0)parts.Add("Key players: "+string.Join(", ",scout.KeyPlayers.Take(5).Select(x=>$"{x.Name} ({x.Position}, OVR {x.Overall})")));return parts.Count==0?scout.SourceEvidence:string.Join("\n",parts);}catch(JsonException){return"Opponent scouting data could not be read.";}}}
    private Character? ManagerCharacter=>Characters.FirstOrDefault(x=>x.Type==CareerCompanion.Core.Domain.CharacterType.Manager&&SquadMemberView.From(x).Active);
    public string ManagerName=>ManagerCharacter?.Name??"No manager detected";
    public string ManagerRelationship{get{if(ManagerCharacter is null)return"Add or synchronize a manager to enable meetings.";var r=_db.GetRelationship(ManagerCharacter.Id);return $"Relationship {Label(r.Score)} | Trust {Label(r.Trust)} | Respect {Label(r.Respect)}";}}
    public string ManagerBriefing{get{if(ManagerCharacter is null)return"The next FIFA synchronization can add the verified club manager automatically.";var state=_db.GetCharacterState(ManagerCharacter.Id);var latest=CurrentCareer is null?null:_db.GetMessages(CurrentCareer.Id,ManagerCharacter.Id).LastOrDefault();return $"Mood: {state.Mood} | Satisfaction: {state.Satisfaction}\n{(latest is null?"No recent meeting or automatic message.":"Latest: "+latest.Content)}";}}
    public string AgentName=>Characters.FirstOrDefault(x=>x.Type==CareerCompanion.Core.Domain.CharacterType.Agent&&SquadMemberView.From(x).Active)?.Name??"No agent detected";

    string _status="Ready";public string Status{get=>_status;set=>Set(ref _status,value);}string _matchResultSummary="";public string MatchResultSummary{get=>_matchResultSummary;set=>Set(ref _matchResultSummary,value);}string _messageGenerationStatus="";public string MessageGenerationStatus{get=>_messageGenerationStatus;set=>Set(ref _messageGenerationStatus,value);}string _interviewGenerationStatus="";public string InterviewGenerationStatus{get=>_interviewGenerationStatus;set=>Set(ref _interviewGenerationStatus,value);}
    public string NewSaveName{get;set;}="My Career";public string NewPlayerName{get;set;}="";public string NewNationality{get;set;}="";public int NewAge{get;set;}=18;public string NewClub{get;set;}="";public string NewLeague{get;set;}="";public string NewSeason{get;set;}="2017/18";public string NewPosition{get;set;}="CAM";public int NewShirtNumber{get;set;}=10;
    public string MatchDate{get;set;}="";public string MatchCompetition{get;set;}="League";public string MatchOpponent{get;set;}="";public bool MatchHome{get;set;}=true;public int TeamScore{get;set;}=0;public int OpponentScore{get;set;}=0;public int Goals{get;set;}=0;public int Assists{get;set;}=0;public double Rating{get;set;}=6.5;public int Minutes{get;set;}=90;private bool _started=true;public bool Started{get=>_started;set{_started=value;StartedKnown=true;OnChanged();OnChanged(nameof(StartedReviewVisibility));}}public bool StartedKnown{get;private set;}=true;public Visibility StartedReviewVisibility=>StartedKnown?Visibility.Collapsed:Visibility.Visible;public bool YellowCard{get;set;}public bool RedCard{get;set;}public bool PenaltyScored{get;set;}public bool PenaltyMissed{get;set;}public bool IsDerby{get;set;}public bool IsMajor{get;set;}public string MatchNextOpponent{get;set;}="";public string MatchNotes{get;set;}="";
    public string CharacterName{get;set;}="";public int CharacterAge{get;set;}=24;public string CharacterNationality{get;set;}="";public string CharacterPosition{get;set;}="CM";public string CharacterRole{get;set;}="Squad Player";public string CharacterType{get;set;}=nameof(CareerCompanion.Core.Domain.CharacterType.Teammate);
    string _messageText="";public string MessageText{get=>_messageText;set=>Set(ref _messageText,value);}public string SelectedScene{get;set;}=nameof(SceneType.PrivateMessage);public string PressAnswer{get;set;}="";public string PressQuestion{get;private set;}="No post-match interview is scheduled.";
    public bool HasActiveInterview=>_activeInterview is not null;
    public Visibility InterviewVisibility=>HasActiveInterview?Visibility.Visible:Visibility.Collapsed;
    public Visibility NoInterviewVisibility=>_latestInterview is null?Visibility.Visible:Visibility.Collapsed;
    public Visibility InterviewCompleteVisibility=>!HasActiveInterview&&_latestInterview is not null?Visibility.Visible:Visibility.Collapsed;
    public string InterviewCompletionText=>_latestInterview?.Status switch{"Completed"=>"Interview complete","Declined"=>"Interview declined",_=>""};
    public string InterviewProgress{get{if(_activeInterview is null)return"";var questions=JsonSerializer.Deserialize<List<string>>(_activeInterview.QuestionsJson)??[];return $"QUESTION {_activeInterview.CurrentQuestion+1} OF {questions.Count} | {_activeInterview.TriggerType.Replace('_',' ')}";}}
    string _defaultModel="gpt-5.6-luna";public string DefaultModel{get=>_defaultModel;set=>Set(ref _defaultModel,value);}string _premiumModel="gpt-5.6-sol";public string PremiumModel{get=>_premiumModel;set=>Set(ref _premiumModel,value);}public bool PremiumRouting{get;set;}=true;public bool AutoTeammates{get;set;}=true;public bool AutoManager{get;set;}=true;public bool AutoNews{get;set;}=true;public bool AutoSocial{get;set;}=true;public bool AutoPress{get;set;}=true;
    bool _debugMode;public bool DebugMode{get=>_debugMode;set{if(Set(ref _debugMode,value))OnChanged(nameof(DebugVisibility));}}public Visibility DebugVisibility=>DebugMode?Visibility.Visible:Visibility.Collapsed;public string DebugText{get;private set;}="";
    string _fifaSyncStatus="Waiting for a FIFA 18 career save.";public string FifaSyncStatus{get=>_fifaSyncStatus;set=>Set(ref _fifaSyncStatus,value);}public string FifaSettingsDirectory{get;private set;}="";public bool AutoFifaWatch{get;set;}=true;public bool AutoFifaSquadSync{get;set;}=true;public bool HasPendingFifaMatch=>PendingMatchReviews.Count>0;
    public Visibility FifaReviewVisibility=>HasPendingFifaMatch?Visibility.Visible:Visibility.Collapsed;
    public string FifaSyncBadge=>HasPendingFifaMatch?"MATCH READY":"FIFA SYNC";
    public string LastFifaSyncText=>CurrentCareer is null?"No linked career":_db.GetSetting($"career:{CurrentCareer.Id}:fifa_last_sync")??"Not synchronized yet";
    public string FifaSourceText=>CurrentCareer is null?FifaSettingsDirectory:_db.GetSetting($"career:{CurrentCareer.Id}:fifa_source")??FifaSettingsDirectory;
    public string MatchReviewCount=>PendingMatchReviews.Count==1?"1 MATCH NEEDS REVIEW":$"{PendingMatchReviews.Count} MATCHES NEED REVIEW";
    public string SelectedReviewDetails=>SelectedMatchReview is null?"Select a detected match.":$"{SelectedMatchReview.Date} | {SelectedMatchReview.Venue} | {SelectedMatchReview.Competition}\n{SelectedMatchReview.Confidence}\n{SelectedMatchReview.Evidence}";
    public int UnreadNotificationCount=>Notifications.Count(x=>!x.IsRead);
    public string NotificationBadge=>UnreadNotificationCount==0?"WORLD UP TO DATE":$"{UnreadNotificationCount} NEW UPDATES";
    public string NotificationNavLabel=>UnreadNotificationCount==0?"WORLD UPDATES":$"WORLD UPDATES ({UnreadNotificationCount})";
    public string LatestHeadline=>News.FirstOrDefault()?.Headline??"No headline yet";
    public string LatestIncoming{get{var item=Notifications.FirstOrDefault(x=>x.Kind is "Message" or "Manager");return item is null?"No incoming character messages yet":$"{item.Title}: {item.Body}";}}
    public string ProgressSummary{get{var latest=ProgressSnapshots.FirstOrDefault();return latest is null?"No FIFA progression baseline yet.":$"{(latest.Overall>0?$"OVR {latest.Overall} | ":"")}Form {latest.Form} | {latest.Appearances} apps | {latest.Goals} goals | {latest.Assists} assists";}}
    private PlayerState PlayerMindset=>CurrentCareer is null?new(0):_db.GetPlayerState(CurrentCareer.Id);
    public string PlayerMindsetTitle=>PlayerMindset.Mood.ToUpperInvariant();
    public string PlayerMindsetSummary=>$"Confidence {PlayerMindset.Confidence} | Pressure {PlayerMindset.Pressure} | Fatigue {PlayerMindset.Fatigue} | Isolation {PlayerMindset.Isolation}";
    public string PlayerMindsetDetail=>PlayerMindset.NeedsSupport?$"{PlayerMindset.LastTrigger}. This is becoming difficult to carry alone.":$"{PlayerMindset.LastTrigger}. Your current state remains manageable.";
    public Visibility RecoveryChoiceVisibility=>CurrentCareer is not null&&MatchHistory.FirstOrDefault() is { } latest&&(latest.Result=="L"||PlayerMindset.NeedsSupport||PlayerMindset.Fatigue>=60)?Visibility.Visible:Visibility.Collapsed;
    public string MatchSubmitLabel=>_editingMatchId is null?"PROCESS MATCH":"SAVE CORRECTION";
    public Visibility MatchEditVisibility=>_editingMatchId is null?Visibility.Collapsed:Visibility.Visible;
    public string SelectedMatchHistoryDetails=>SelectedLoggedMatch is null?"Select a logged match to edit or delete.":$"{SelectedLoggedMatch.Input.Date} | {SelectedLoggedMatch.Input.Competition} | {(SelectedLoggedMatch.Input.IsHome?"HOME":"AWAY")}\n{SelectedLoggedMatch.Input.TeamScore}-{SelectedLoggedMatch.Input.OpponentScore} vs {SelectedLoggedMatch.Input.Opponent} | Rating {SelectedLoggedMatch.Input.Rating:0.0} | {SelectedLoggedMatch.Input.Goals} goals | {SelectedLoggedMatch.Input.Assists} assists";
    public bool CanAutoLinkPendingFifa=>_pendingFifa is not null&&Careers.All(x=>x.SaveName.Contains("Demo",StringComparison.OrdinalIgnoreCase));

    public void ReloadCareers(){Careers.Clear();foreach(var c in _db.GetCareers())Careers.Add(c);}
    public void CreateCareer(){if(string.IsNullOrWhiteSpace(NewPlayerName)||string.IsNullOrWhiteSpace(NewClub))throw new InvalidOperationException("Player name and club are required.");var id=_db.CreateCareer(NewSaveName,NewPlayerName,NewNationality,NewAge,NewClub,NewLeague,NewSeason,NewPosition,NewShirtNumber);ReloadCareers();CurrentCareer=Careers.Single(x=>x.Id==id);Status="Career created";}
    public void AddCharacter(){RequireCareer();if(string.IsNullOrWhiteSpace(CharacterName))throw new InvalidOperationException("Character name is required.");_db.AddCharacter(CurrentCareer!.Id,CharacterName,CharacterAge,CharacterNationality,CurrentCareer.Club,CharacterPosition,CharacterRole,Enum.Parse<CharacterType>(CharacterType));Refresh();Status=$"Added {CharacterName}";CharacterName="";}
    public void ProcessMatch()
    {
        RequireCareer();if(string.IsNullOrWhiteSpace(MatchOpponent))throw new InvalidOperationException("Opponent is required.");if(!DateTime.TryParse(MatchDate,out _))throw new InvalidOperationException("Enter a valid match date.");if(TeamScore<0||OpponentScore<0||Goals<0||Assists<0||Minutes is <0 or >130||Rating is <0 or >10)throw new InvalidOperationException("Check the score, statistics, minutes, and rating values.");
        var career=CurrentCareer!;var review=SelectedMatchReview;var importSnapshot=_loadedReviewSnapshot;var importingReview=_editingMatchId is null&&review is not null&&_loadedReviewId==review.Id&&importSnapshot?.LatestMatch?.EventKey==review.Review.EventKey;if(importingReview&&review!.Review.CareerId!=career.Id)throw new InvalidOperationException("This FIFA review belongs to another career. Reopen it from that career's Review Inbox.");if(importingReview&&PendingMatchReviews.Any(x=>x.Id!=review!.Id&&string.CompareOrdinal(x.Date,review.Date)<0))throw new InvalidOperationException("Import the oldest pending FIFA match first so cumulative statistics stay chronological.");
        var input=new MatchInput(MatchDate,MatchCompetition,MatchOpponent,MatchHome,TeamScore,OpponentScore,Started,Minutes,Goals,Assists,Rating,YellowCard,RedCard,PenaltyScored,PenaltyMissed,MatchNotes,string.IsNullOrWhiteSpace(MatchNextOpponent)?null:MatchNextOpponent,IsDerby,IsMajor,importingReview?StartedKnown:true);
        var correcting=_editingMatchId is not null;var result=correcting?_careers.UpdateMatch(career.Id,_editingMatchId!.Value,input):_careers.ProcessMatch(career.Id,input,importingReview?"FIFA 18 Save":null,importingReview?importSnapshot!.LatestMatch!.EventKey:null);if(correcting)new PlayerPsychologyService(_db).RebuildBeforeMatch(career.Id,result.Match.Id);_db.CompleteMatchingFixture(career.Id,input.Date,input.Opponent);var media=AutoNews||AutoSocial?new MediaService(_db).GenerateDeterministic(career.Id,result.Events,AutoNews,AutoSocial):new MediaGenerationResult(0,0);var interview=new PostMatchInterviewService(_db).CreateIfEligible(career.Id,result,AutoPress);var world=new AutomaticWorldService(_db);var automatic=world.ApplyMatch(result,AutoTeammates,AutoManager,interview is not null,media.NewsItems>0,media.SocialPosts>0);if(correcting)world.RebuildMatchCharacterStates(career.Id);
        if(importingReview&&importSnapshot?.LatestMatch is not null){var eventKey=importSnapshot.LatestMatch.EventKey;_db.RecordProviderImport(career.Id,"FIFA 18 Save",eventKey,importSnapshot.SourcePath,importSnapshot.FileFingerprint,importSnapshot.CapturedAt,JsonSerializer.Serialize(importSnapshot.State));_db.CompleteProviderMatch(career.Id,"FIFA 18 Save",eventKey);_db.SetMatchReviewStatus(career.Id,"FIFA 18 Save",eventKey,"Imported");_db.MarkNotificationRead(career.Id,$"review:{eventKey}");_db.UpdateCareerFromProvider(career.Id,importSnapshot.PlayerName,importSnapshot.NationalityName,importSnapshot.Age,importSnapshot.ClubName,importSnapshot.LeagueName,importSnapshot.Season,importSnapshot.CurrentDate,importSnapshot.Position,importSnapshot.ShirtNumber);_db.SetSetting($"career:{career.Id}:fifa_player_id",importSnapshot.PlayerId.ToString());FifaSyncStatus="FIFA match imported. Watching for the next completed save.";_pendingFifa=null;_loadedReviewId=null;_loadedReviewSnapshot=null;SelectedMatchReview=null;ReloadMatchReviews();NotifyFifaState();ReloadCareers();_currentCareer=Careers.FirstOrDefault(x=>x.Id==career.Id)??career;OnChanged(nameof(CurrentCareer));}
        _editingMatchId=null;SelectedLoggedMatch=null;OnChanged(nameof(MatchSubmitLabel));OnChanged(nameof(MatchEditVisibility));MatchResultSummary=$"{(correcting?"Correction saved":"Saved")}. Generated {result.Events.Count} events and {automatic.IncomingMessages} incoming character reactions"+(interview is null?". No post-match interview requested.":". A post-match interview is waiting in the Press Room.")+(result.Narratives.Count>0?$" Active narratives: {string.Join(", ",result.Narratives)}.":"");Status=correcting?"Match corrected and world effects rebuilt":"World updated automatically";Refresh();
    }

    public void EditSelectedMatch(){RequireCareer();var match=SelectedLoggedMatch??throw new InvalidOperationException("Select a logged match first.");_editingMatchId=match.Id;_loadedReviewId=null;_loadedReviewSnapshot=null;PopulateMatch(match.Input);OnChanged(nameof(MatchSubmitLabel));OnChanged(nameof(MatchEditVisibility));MatchResultSummary=_db.IsProviderMatch(match.CareerId,match.Id)?"Editing a FIFA synchronized match. The provider link and automatic baseline will be preserved.":"Editing a manually logged match.";}
    public void CancelMatchEdit(){_editingMatchId=null;SelectedLoggedMatch=null;ResetMatchForm();MatchResultSummary="";OnChanged(nameof(MatchSubmitLabel));OnChanged(nameof(MatchEditVisibility));}
    public void StartNewManualMatch(){_editingMatchId=null;_loadedReviewId=null;_loadedReviewSnapshot=null;SelectedLoggedMatch=null;ResetMatchForm();MatchResultSummary="Manual match form ready. Pending FIFA reviews remain safely in the Review Inbox.";OnChanged(nameof(MatchSubmitLabel));OnChanged(nameof(MatchEditVisibility));}
    public void DeleteSelectedMatch(){RequireCareer();var match=SelectedLoggedMatch??throw new InvalidOperationException("Select a logged match first.");_db.DeleteManualMatch(CurrentCareer!.Id,match.Id);new AutomaticWorldService(_db).RebuildMatchCharacterStates(CurrentCareer.Id);_editingMatchId=null;SelectedLoggedMatch=null;ResetMatchForm();Status="Match and its generated world activity deleted";MatchResultSummary="The selected manual match was removed.";Refresh();}
    public bool ChooseRecovery(string choice)
    {
        RequireCareer();var result=new PlayerPsychologyService(_db).ChooseRecovery(CurrentCareer!.Id,choice);Refresh();Status=result.Summary;if(result.Applied&&result.SupporterId is { } id){SelectedCharacter=Characters.FirstOrDefault(x=>x.Id==id);MessageText="That result hit me harder than I expected. Can we talk?";SelectedScene=SceneType.PrivateMessage.ToString();OnChanged(nameof(SelectedScene));return SelectedCharacter is not null;}return false;
    }

    public async Task<Fifa18ScanResult> ScanFifaSaveAsync(bool automatic=false,CancellationToken ct=default)
    {
        FifaSyncStatus=automatic?"FIFA save changed; reading a stable snapshot...":"Scanning the newest FIFA 18 career save...";
        var provider=new Fifa18SaveCareerDataProvider(_db);var scanCareerId=CurrentCareer?.Id;var parsed=await provider.ParseLatestAsync(scanCareerId,FifaSettingsDirectory,ct);if(CurrentCareer?.Id!=scanCareerId)return await ScanFifaSaveAsync(automatic,ct);_db.Log("fifa_sync",$"Parsed player={parsed.PlayerId}; career date={parsed.CurrentDate}; automatic={automatic}.");var routedId=_db.FindCareerIdByFifaPlayerId(parsed.PlayerId);if(routedId is not null&&CurrentCareer?.Id!=routedId){var routed=Careers.FirstOrDefault(x=>x.Id==routedId)??_db.GetCareer(routedId.Value);CurrentCareer=routed;parsed=await provider.ParseLatestAsync(routedId,FifaSettingsDirectory,ct);FifaSyncStatus=$"Automatically opened {routed.SaveName} for the detected FIFA player.";}
        if(CurrentCareer is null){_pendingFifa=parsed;FifaSyncStatus=$"Found {parsed.PlayerName} at {parsed.ClubName}. Create a linked career to import it.";NotifyFifaState();return new(Fifa18ScanDisposition.NoCareerSelected,parsed,FifaSyncStatus);}
        var linkedId=_db.GetSetting($"career:{CurrentCareer.Id}:fifa_player_id");var linked=linkedId==parsed.PlayerId.ToString();var sameIdentity=CurrentCareer.PlayerName.Contains(parsed.PlayerName,StringComparison.OrdinalIgnoreCase)||parsed.PlayerName.Contains(CurrentCareer.PlayerName,StringComparison.OrdinalIgnoreCase);var sameClub=string.Equals(CurrentCareer.Club,parsed.ClubName,StringComparison.OrdinalIgnoreCase);
        if(!linked&&(!sameIdentity||!sameClub)){_pendingFifa=parsed;FifaSyncStatus=$"Save belongs to {parsed.PlayerName} at {parsed.ClubName}; active companion career is {CurrentCareer.PlayerName} at {CurrentCareer.Club}.";NotifyFifaState();return new(Fifa18ScanDisposition.CareerMismatch,parsed,FifaSyncStatus);}
        var careerId=CurrentCareer.Id;var previousProgress=_db.GetLatestCareerProgressSnapshot(careerId);_db.SetSetting($"career:{careerId}:fifa_player_id",parsed.PlayerId.ToString());_db.UpdateCareerFromProvider(careerId,parsed.PlayerName,parsed.NationalityName,parsed.Age,parsed.ClubName,parsed.LeagueName,parsed.Season,parsed.CurrentDate,parsed.Position,parsed.ShirtNumber);var playerInjured=parsed.PlayerInjuryKnown?parsed.PlayerInjured:previousProgress?.Injured??false;var progress=new CareerProgressSnapshot(0,careerId,parsed.CapturedAt,parsed.CurrentDate,parsed.ClubName,parsed.LeagueName,parsed.Position,parsed.ShirtNumber,parsed.PlayerOverall,parsed.PlayerForm,playerInjured,parsed.State.Appearances,parsed.State.Goals,parsed.State.Assists,parsed.State.YellowCards,parsed.State.RedCards,parsed.FileFingerprint);new AutomaticWorldService(_db).ApplyProgress(careerId,progress,previousProgress);ReloadCareers();_currentCareer=Careers.FirstOrDefault(x=>x.Id==careerId)??CurrentCareer;OnChanged(nameof(CurrentCareer));var supporting=SyncSupportingFacts(careerId,parsed);var supportingMessage=DescribeSupportingSync(supporting,parsed);RecordFifaSync(parsed);
        if(parsed.LatestMatch is null){_pendingFifa=null;NotifyFifaState();FifaSyncStatus=$"Save synchronized{supportingMessage}; no player match is available to import.";return new(Fifa18ScanDisposition.NoNewMatch,parsed,FifaSyncStatus);}
        if(_db.HasProviderImport(CurrentCareer.Id,"FIFA 18 Save",parsed.LatestMatch.EventKey)){_db.SetMatchReviewStatus(CurrentCareer.Id,"FIFA 18 Save",parsed.LatestMatch.EventKey,"Imported");_db.MarkNotificationRead(CurrentCareer.Id,$"review:{parsed.LatestMatch.EventKey}");_pendingFifa=null;ReloadMatchReviews();FifaSyncStatus=$"Save synchronized{supportingMessage}; its latest match has already been imported.";return new(Fifa18ScanDisposition.NoNewMatch,parsed,FifaSyncStatus);}
        if(_db.GetMatchReviewStatus(CurrentCareer.Id,"FIFA 18 Save",parsed.LatestMatch.EventKey)=="Dismissed"){_pendingFifa=null;ReloadMatchReviews();FifaSyncStatus=$"Save synchronized{supportingMessage}; its latest detected match was dismissed.";return new(Fifa18ScanDisposition.NoNewMatch,parsed,FifaSyncStatus);}
        _db.StageMatchReview(careerId,"FIFA 18 Save",parsed.LatestMatch.EventKey,parsed.SourcePath,parsed.FileFingerprint,parsed.CapturedAt,JsonSerializer.Serialize(parsed.LatestMatch),JsonSerializer.Serialize(parsed));_pendingFifa=parsed;ReloadMatchReviews();
        if(automatic&&!parsed.LatestMatch.RequiresReview&&parsed.LatestMatch.Confidence>=95)
        {
            SelectedMatchReview=PendingMatchReviews.First(x=>x.Review.EventKey==parsed.LatestMatch.EventKey);_loadedReviewId=SelectedMatchReview.Id;_loadedReviewSnapshot=parsed;PopulateMatch(parsed.LatestMatch);ProcessMatch();FifaSyncStatus=$"Verified FIFA match auto-imported: {parsed.LatestMatch.TeamScore}-{parsed.LatestMatch.OpponentScore} vs {parsed.LatestMatch.Opponent}.";NotifyFifaState();return new(Fifa18ScanDisposition.MatchAutoImported,parsed,FifaSyncStatus);
        }
        _db.AddNotification(careerId,"Review","Match detected",$"{parsed.LatestMatch.TeamScore}-{parsed.LatestMatch.OpponentScore} vs {parsed.LatestMatch.Opponent} is ready for review.","Review",85,$"review:{parsed.LatestMatch.EventKey}",DateTime.TryParse(parsed.CurrentDate,out var careerDate)?careerDate:parsed.CapturedAt);Refresh();
        FifaSyncStatus=$"New match detected: {parsed.LatestMatch.TeamScore}-{parsed.LatestMatch.OpponentScore} vs {parsed.LatestMatch.Opponent} ({parsed.LatestMatch.Confidence}% confidence). Review and import. Supporting facts synchronized{supportingMessage}.";NotifyFifaState();return new(Fifa18ScanDisposition.MatchDetected,parsed,FifaSyncStatus);
    }

    public void CreateCareerFromPendingFifa()
    {
        if(_pendingFifa is null)throw new InvalidOperationException("Scan a FIFA save first.");var p=_pendingFifa;_db.Log("fifa_sync",$"Linking player={p.PlayerId}; career date={p.CurrentDate}.");var id=_db.CreateCareer(Path.GetFileName(p.SourcePath),p.PlayerName,p.NationalityName,p.Age,p.ClubName,p.LeagueName,p.Season,p.Position,p.ShirtNumber,p.CurrentDate);_db.UpdateCareerFromProvider(id,p.PlayerName,p.NationalityName,p.Age,p.ClubName,p.LeagueName,p.Season,p.CurrentDate,p.Position,p.ShirtNumber);_db.SetSetting($"career:{id}:fifa_player_id",p.PlayerId.ToString());ReloadCareers();CurrentCareer=Careers.Single(x=>x.Id==id);new AutomaticWorldService(_db).ApplyProgress(id,new(0,id,p.CapturedAt,p.CurrentDate,p.ClubName,p.LeagueName,p.Position,p.ShirtNumber,p.PlayerOverall,p.PlayerForm,p.PlayerInjuryKnown&&p.PlayerInjured,p.State.Appearances,p.State.Goals,p.State.Assists,p.State.YellowCards,p.State.RedCards,p.FileFingerprint),null);var supporting=SyncSupportingFacts(id,p);RecordFifaSync(p);if(p.LatestMatch is not null){_db.StageMatchReview(id,"FIFA 18 Save",p.LatestMatch.EventKey,p.SourcePath,p.FileFingerprint,p.CapturedAt,JsonSerializer.Serialize(p.LatestMatch),JsonSerializer.Serialize(p));_db.AddNotification(id,"Review","First FIFA match needs a baseline review",$"{p.LatestMatch.TeamScore}-{p.LatestMatch.OpponentScore} vs {p.LatestMatch.Opponent} is ready for review.","Review",85,$"review:{p.LatestMatch.EventKey}",DateTime.TryParse(p.CurrentDate,out var date)?date:p.CapturedAt);ReloadMatchReviews();SelectedMatchReview=PendingMatchReviews.FirstOrDefault(x=>x.Review.EventKey==p.LatestMatch.EventKey);}FifaSyncStatus=$"Linked career created for {p.PlayerName}{DescribeSupportingSync(supporting,p)}. Review the first detected match to establish the automatic baseline.";Refresh();NotifyFifaState();
    }

    private Fifa18SupportingSyncResult SyncSupportingFacts(long careerId,Fifa18ParsedCareer parsed){var result=new Fifa18ImportService(_db).SyncSupportingFacts(careerId,parsed,AutoFifaSquadSync,AutoTeammates,AutoManager);Refresh();return result;}
    private static string DescribeSupportingSync(Fifa18SupportingSyncResult result,Fifa18ParsedCareer parsed){var parts=new List<string>();if(result.Squad is { } squad)parts.Add($"{parsed.Squad.Count} teammates synced ({squad.Added} new, {squad.MarkedInactive} departed)");if(result.FixtureUpdated&&parsed.NextFixture is { } fixture)parts.Add($"next fixture: {(fixture.IsHome?"vs":"at")} {fixture.Opponent}");return parts.Count==0?"":" | "+string.Join(" | ",parts);}

    public void PopulatePendingMatchForReview()
    {
        var review=SelectedMatchReview??PendingMatchReviews.FirstOrDefault()??throw new InvalidOperationException("No FIFA match is waiting for review.");
        SelectedMatchReview=review;_loadedReviewId=review.Id;_loadedReviewSnapshot=review.Snapshot;PopulateMatch(review.Match);NotifyFifaState();
    }
    public void DismissSelectedMatchReview()
    {
        var review=SelectedMatchReview??throw new InvalidOperationException("Select a match to dismiss.");
        _db.SetMatchReviewStatus(review.Id,"Dismissed");_db.MarkNotificationRead(review.Review.CareerId,$"review:{review.Review.EventKey}");if(_pendingFifa?.LatestMatch?.EventKey==review.Review.EventKey)_pendingFifa=null;_loadedReviewId=null;_loadedReviewSnapshot=null;SelectedMatchReview=null;ReloadMatchReviews();FifaSyncStatus="Detected match dismissed. It will not be offered again.";Refresh();NotifyFifaState();
    }
    public bool PrepareConversation(CharacterType type,SceneType scene)
    {
        var character=Characters.FirstOrDefault(x=>x.Type==type&&SquadMemberView.From(x).Active)??Characters.FirstOrDefault(x=>x.Type==type);
        if(character is null)return false;
        SelectedCharacter=character;SelectedScene=scene.ToString();MessageText=type switch{CareerCompanion.Core.Domain.CharacterType.Manager=>UpcomingFixture is null?"I would like to discuss my role and recent form.":$"I want to discuss the plan for {PreMatchOpponent}.",CareerCompanion.Core.Domain.CharacterType.Agent=>"I want to review how my career is progressing and what we should focus on next.",_=>UpcomingFixture is null?"How are things in the squad?":$"How are you feeling before the match against {PreMatchOpponent}?"};
        OnChanged(nameof(SelectedScene));return true;
    }
    public bool PrepareAgentConversation()=>PrepareConversation(CareerCompanion.Core.Domain.CharacterType.Agent,SceneType.TransferDiscussion);
    public void MarkFifaSyncFailure(string message){FifaSyncStatus="FIFA synchronization failed: "+message;if(CurrentCareer is not null)_db.SetSetting($"career:{CurrentCareer.Id}:fifa_last_error",message);NotifyFifaState();}
    private void RecordFifaSync(Fifa18ParsedCareer parsed)
    {
        if(CurrentCareer is null)return;
        _db.SetSetting($"career:{CurrentCareer.Id}:fifa_last_sync",$"Last synchronized {DateTime.Now:dd MMM yyyy, HH:mm}");
        _db.SetSetting($"career:{CurrentCareer.Id}:fifa_source",Path.GetFileName(parsed.SourcePath));
        _db.SetSetting($"career:{CurrentCareer.Id}:fifa_last_error","");NotifyFifaState();
    }
    private void NotifyFifaState(){ReloadInterview();NotifyImmersionState();OnChanged(nameof(HasPendingFifaMatch));OnChanged(nameof(FifaReviewVisibility));OnChanged(nameof(FifaSyncBadge));OnChanged(nameof(LastFifaSyncText));OnChanged(nameof(FifaSourceText));OnChanged(nameof(MatchReviewCount));}
    private void ReloadMatchReviews()
    {
        var selectedId=SelectedMatchReview?.Id;PendingMatchReviews.Clear();if(CurrentCareer is not null)foreach(var item in _db.GetMatchReviews(CurrentCareer.Id,"Pending"))PendingMatchReviews.Add(MatchReviewView.From(item));SelectedMatchReview=PendingMatchReviews.FirstOrDefault(x=>x.Id==selectedId)??PendingMatchReviews.FirstOrDefault();NotifyFifaState();
    }
    private void RebuildSquadViews()
    {
        var selectedId=SelectedSquadMember?.Id;SquadMembers.Clear();FormerTeammates.Clear();OtherCharacters.Clear();
        var teammates=Characters.Where(x=>x.Type==CareerCompanion.Core.Domain.CharacterType.Teammate).Select(SquadMemberView.From).ToList();
        foreach(var player in teammates.Where(x=>!x.Active))FormerTeammates.Add(player);
        IEnumerable<SquadMemberView> active=teammates.Where(x=>x.Active);
        active=SelectedSquadFilter switch
        {
            "Goalkeepers"=>active.Where(x=>x.Position=="GK"),
            "Defenders"=>active.Where(x=>new[]{"CB","LB","RB","LWB","RWB","SW"}.Contains(x.Position)),
            "Midfielders"=>active.Where(x=>new[]{"CDM","CM","CAM","LM","RM"}.Contains(x.Position)),
            "Forwards"=>active.Where(x=>new[]{"LW","RW","CF","ST"}.Contains(x.Position)),
            "Injured"=>active.Where(x=>x.Injured),
            _=>active
        };
        foreach(var player in active.OrderBy(x=>x.Position).ThenByDescending(x=>x.Overall))SquadMembers.Add(player);
        foreach(var character in Characters.Where(x=>x.Type!=CareerCompanion.Core.Domain.CharacterType.Teammate))OtherCharacters.Add(character);
        SelectedSquadMember=selectedId is null?null:SquadMembers.FirstOrDefault(x=>x.Id==selectedId);
        OnChanged(nameof(PreMatchAvailability));OnChanged(nameof(PreMatchKeyPlayers));OnChanged(nameof(PreMatchIntel));
    }

    private void PopulateMatch(Fifa18DetectedMatch m){MatchDate=m.Date;MatchCompetition=m.Competition;MatchOpponent=m.Opponent;MatchHome=m.IsHome;TeamScore=m.TeamScore;OpponentScore=m.OpponentScore;_started=m.Started;StartedKnown=m.StartedKnown;Minutes=m.Minutes;Goals=m.Goals;Assists=m.Assists;Rating=m.Rating;YellowCard=m.YellowCard;RedCard=m.RedCard;PenaltyScored=false;PenaltyMissed=false;IsDerby=false;IsMajor=false;MatchNextOpponent="";MatchNotes=m.Evidence;foreach(var name in new[]{nameof(MatchDate),nameof(MatchCompetition),nameof(MatchOpponent),nameof(MatchHome),nameof(TeamScore),nameof(OpponentScore),nameof(Started),nameof(StartedReviewVisibility),nameof(Minutes),nameof(Goals),nameof(Assists),nameof(Rating),nameof(YellowCard),nameof(RedCard),nameof(PenaltyScored),nameof(PenaltyMissed),nameof(IsDerby),nameof(IsMajor),nameof(MatchNextOpponent),nameof(MatchNotes)})OnChanged(name);}
    private void PopulateMatch(MatchInput m){MatchDate=m.Date;MatchCompetition=m.Competition;MatchOpponent=m.Opponent;MatchHome=m.IsHome;TeamScore=m.TeamScore;OpponentScore=m.OpponentScore;_started=m.Started;StartedKnown=m.StartedKnown;Minutes=m.Minutes;Goals=m.Goals;Assists=m.Assists;Rating=m.Rating;YellowCard=m.YellowCard;RedCard=m.RedCard;PenaltyScored=m.PenaltyScored;PenaltyMissed=m.PenaltyMissed;IsDerby=m.IsDerby;IsMajor=m.IsMajorFixture;MatchNextOpponent=m.NextOpponent??"";MatchNotes=m.Notes;NotifyMatchForm();}
    private void ResetMatchForm(){MatchDate=CurrentCareer?.CurrentDate??DateTime.Today.ToString("yyyy-MM-dd");MatchCompetition="League";MatchOpponent="";MatchHome=true;TeamScore=0;OpponentScore=0;_started=true;StartedKnown=true;Minutes=90;Goals=0;Assists=0;Rating=6.5;YellowCard=false;RedCard=false;PenaltyScored=false;PenaltyMissed=false;IsDerby=false;IsMajor=false;MatchNextOpponent="";MatchNotes="";NotifyMatchForm();}
    private void NotifyMatchForm(){foreach(var name in new[]{nameof(MatchDate),nameof(MatchCompetition),nameof(MatchOpponent),nameof(MatchHome),nameof(TeamScore),nameof(OpponentScore),nameof(Started),nameof(StartedReviewVisibility),nameof(Minutes),nameof(Goals),nameof(Assists),nameof(Rating),nameof(YellowCard),nameof(RedCard),nameof(PenaltyScored),nameof(PenaltyMissed),nameof(IsDerby),nameof(IsMajor),nameof(MatchNextOpponent),nameof(MatchNotes)})OnChanged(name);}
    public async Task SendMessageAsync(){RequireCareer();if(SelectedCharacter is null)throw new InvalidOperationException("Select a character first.");if(string.IsNullOrWhiteSpace(MessageText))return;MessageGenerationStatus="Generating in the background...";var key=GetApiKey();using var http=new HttpClient{Timeout=TimeSpan.FromSeconds(45)};ILlmProvider provider=string.IsNullOrWhiteSpace(key)?new OfflineLlmProvider():new OpenAIProvider(http,()=>key);try{var service=new ConversationService(_db,provider);var scene=Enum.Parse<SceneType>(SelectedScene);var result=await service.SendAsync(CurrentCareer!.Id,SelectedCharacter.Id,scene,MessageText,RouteModel(Events.FirstOrDefault()?.Importance??0,scene));MessageText="";MessageGenerationStatus=$"Reply received | {result.InputTokens+result.OutputTokens} tokens";LoadMessages();OnChanged(nameof(SelectedRelationship));NotifyImmersionState();}catch(LlmUnavailableException e){MessageGenerationStatus=e.Message;}catch(LlmRateLimitException e){MessageGenerationStatus=e.Message;}}
    public async Task RunAutomaticGenerationAsync(CancellationToken ct=default)
    {
        if(_automaticGenerationBusy||CurrentCareer is null)return;var key=GetApiKey();if(string.IsNullOrWhiteSpace(key))return;_automaticGenerationBusy=true;var careerId=CurrentCareer.Id;
        try{using var http=new HttpClient{Timeout=TimeSpan.FromSeconds(45)};var result=await new AutomaticDialogueService(_db,new OpenAIProvider(http,()=>key)).ProcessPendingAsync(careerId,DefaultModel,PremiumModel,PremiumRouting,4,ct);if(result.Completed>0){MessageGenerationStatus=$"{result.Completed} incoming reaction{(result.Completed==1?"":"s")} written by AI";if(CurrentCareer?.Id==careerId)Refresh();}}
        finally{_automaticGenerationBusy=false;}
    }
    public async Task RecordPressAsync()
    {
        RequireCareer();var interview=_activeInterview??throw new InvalidOperationException("No post-match interview is scheduled.");if(string.IsNullOrWhiteSpace(PressAnswer))throw new InvalidOperationException("Enter a response first.");var career=CurrentCareer!;
        var journalist=Characters.FirstOrDefault(c=>c.Type==CareerCompanion.Core.Domain.CharacterType.Journalist);if(journalist is null){var id=_db.AddCharacter(career.Id,"Press Pool",35,"",career.Club,"Media","Journalist",CareerCompanion.Core.Domain.CharacterType.Journalist);Refresh();journalist=Characters.Single(c=>c.Id==id);}
        var answer=PressAnswer.Trim();var question=PressQuestion;var questions=JsonSerializer.Deserialize<List<string>>(interview.QuestionsJson)??[];var turns=ReadInterviewTurns(interview.AnswersJson);var next=interview.CurrentQuestion+1;var complete=next>=questions.Count;var fallbackNext=complete?null:questions[next];InterviewGenerationStatus="Journalist is responding...";
        var key=GetApiKey();using var http=new HttpClient{Timeout=TimeSpan.FromSeconds(45)};ILlmProvider provider=string.IsNullOrWhiteSpace(key)?new OfflineLlmProvider():new OpenAIProvider(http,()=>key);var reply=await new PostMatchInterviewService(_db).GenerateReplyAsync(interview,question,answer,fallbackNext,provider,RouteModel(interview.Importance,SceneType.PressConference));
        var careerTime=DateTime.TryParse(career.CurrentDate,out var parsedDate)?parsedDate:DateTime.UtcNow;var conv=_db.StartConversation(career.Id,journalist.Id,SceneType.PressConference,JsonSerializer.Serialize(new{interviewId=interview.Id,question}),careerTime);_db.AddMessage(conv,"journalist",question,careerTime);_db.AddMessage(conv,"user",answer,careerTime);_db.AddMessage(conv,"journalist",reply.JournalistResponse,careerTime);_db.AddMemory(career.Id,journalist.Id,null,$"Post-match statement: {answer}",Math.Clamp(interview.Importance,45,85),0,"post-match interview",false,careerTime);
        turns.Add(new(question,answer,reply.JournalistResponse,reply.AiGenerated));if(!complete)questions[next]=reply.JournalistResponse;_db.UpdatePostMatchInterviewDialogue(interview.Id,JsonSerializer.Serialize(questions),JsonSerializer.Serialize(turns),next,complete?"Completed":"Pending");if(complete)_db.MarkNotificationRead(career.Id,$"interview:{interview.MatchId}");new AutomaticWorldService(_db).ApplyPublicStatement(career.Id,interview.Id,interview.CurrentQuestion,answer,interview.Importance);PressAnswer="";OnChanged(nameof(PressAnswer));InterviewGenerationStatus=reply.AiGenerated?"Live journalist response generated":"Offline journalist fallback used";Status=complete?"Post-match interview completed":"Journalist asked a follow-up";ReloadInterview();Refresh();
    }
    public void DeclineInterview(){if(_activeInterview is null)throw new InvalidOperationException("No post-match interview is scheduled.");_db.UpdatePostMatchInterview(_activeInterview.Id,_activeInterview.AnswersJson,_activeInterview.CurrentQuestion,"Declined");_db.MarkNotificationRead(_activeInterview.CareerId,$"interview:{_activeInterview.MatchId}");Status="Post-match interview declined";ReloadInterview();Refresh();}
    public void MarkActiveInterviewRead(){if(_activeInterview is null)return;_db.MarkNotificationRead(_activeInterview.CareerId,$"interview:{_activeInterview.MatchId}");Refresh();}
    public void SaveSettings(string? key){if(!string.IsNullOrWhiteSpace(key))_db.SetSetting("openai_api_key",SecretStore.Protect(key));foreach(var p in new Dictionary<string,string>{{"default_model",DefaultModel},{"premium_model",PremiumModel},{"premium_routing",PremiumRouting.ToString()},{"auto_teammates",AutoTeammates.ToString()},{"auto_manager",AutoManager.ToString()},{"auto_news",AutoNews.ToString()},{"auto_social",AutoSocial.ToString()},{"auto_press",AutoPress.ToString()},{"debug_mode",DebugMode.ToString()},{"auto_fifa_watch",AutoFifaWatch.ToString()},{"auto_fifa_squad_sync",AutoFifaSquadSync.ToString()}})_db.SetSetting(p.Key,p.Value);Status="Settings saved";}
    public void Backup(string path){_db.Backup(path);Status=$"Backup saved: {path}";}
    public void Restore(string path){_db.Restore(path);ReloadCareers();CurrentCareer=Careers.FirstOrDefault();Status="Backup restored";}
    private string GetApiKey(){var env=Environment.GetEnvironmentVariable("OPENAI_API_KEY");if(!string.IsNullOrWhiteSpace(env))return env;var x=_db.GetSetting("openai_api_key");return string.IsNullOrWhiteSpace(x)?"":SecretStore.Unprotect(x);}
    private string RouteModel(int importance,SceneType scene)=>PremiumRouting&&(importance>=75||scene is SceneType.Conflict or SceneType.TransferDiscussion)?PremiumModel:DefaultModel;
    private void LoadSettings(){DefaultModel=_db.GetSetting("default_model")??Environment.GetEnvironmentVariable("OPENAI_DEFAULT_MODEL")??"gpt-5.6-luna";PremiumModel=_db.GetSetting("premium_model")??Environment.GetEnvironmentVariable("OPENAI_PREMIUM_MODEL")??"gpt-5.6-sol";PremiumRouting=B("premium_routing",true);AutoTeammates=B("auto_teammates",true);AutoManager=B("auto_manager",true);AutoNews=B("auto_news",true);AutoSocial=B("auto_social",true);AutoPress=B("auto_press",true);DebugMode=B("debug_mode",false);AutoFifaWatch=B("auto_fifa_watch",true);AutoFifaSquadSync=B("auto_fifa_squad_sync",true);}
    private bool B(string key,bool fallback)=>bool.TryParse(_db.GetSetting(key),out var x)?x:fallback;
    private void RequireCareer(){if(CurrentCareer is null)throw new InvalidOperationException("Create or open a career first.");}
    private void LoadMessages(){Messages.Clear();if(CurrentCareer is null||SelectedCharacter is null)return;foreach(var m in _db.GetMessages(CurrentCareer.Id,SelectedCharacter.Id))Messages.Add(m);}
    private void ReloadInterview()
    {
        _activeInterview=CurrentCareer is null?null:_db.GetPendingPostMatchInterview(CurrentCareer.Id);var latestMatch=CurrentCareer is null?null:_db.GetMatches(CurrentCareer.Id,1).LastOrDefault();_latestInterview=latestMatch is null?null:_db.GetPostMatchInterview(CurrentCareer!.Id,latestMatch.Id);var shown=_activeInterview??_latestInterview;var questions=_activeInterview is null?[]:JsonSerializer.Deserialize<List<string>>(_activeInterview.QuestionsJson)??[];PressQuestion=_activeInterview is not null&&_activeInterview.CurrentQuestion<questions.Count?questions[_activeInterview.CurrentQuestion]:"No post-match interview is scheduled. Routine matches do not automatically generate media duties.";InterviewTranscript.Clear();if(shown is not null){var turns=ReadInterviewTurns(shown.AnswersJson);for(var i=0;i<turns.Count;i++){var turn=turns[i];if(i==0)InterviewTranscript.Add("JOURNALIST: "+turn.Question);InterviewTranscript.Add("YOU: "+turn.Answer);InterviewTranscript.Add("JOURNALIST: "+turn.JournalistResponse);}}OnChanged(nameof(PressQuestion));OnChanged(nameof(HasActiveInterview));OnChanged(nameof(InterviewVisibility));OnChanged(nameof(NoInterviewVisibility));OnChanged(nameof(InterviewCompleteVisibility));OnChanged(nameof(InterviewCompletionText));OnChanged(nameof(InterviewProgress));
    }
    private static List<InterviewTurn> ReadInterviewTurns(string json)
    {
        try{return JsonSerializer.Deserialize<List<InterviewTurn>>(json)??[];}catch(JsonException){try{return (JsonSerializer.Deserialize<List<string>>(json)??[]).Select(x=>new InterviewTurn("Previous question",x,"",false)).ToList();}catch(JsonException){return[];}}
    }
    public void Refresh(){Characters.Clear();MatchHistory.Clear();Fixtures.Clear();Events.Clear();News.Clear();Social.Clear();Notifications.Clear();ProgressSnapshots.Clear();DashboardItems.Clear();ReloadMatchReviews();if(CurrentCareer is null){RebuildSquadViews();NotifyFifaState();return;}_db.ResolveObsoleteNotifications(CurrentCareer.Id);foreach(var x in _db.GetCharacters(CurrentCareer.Id))Characters.Add(x);foreach(var x in _db.GetFixtures(CurrentCareer.Id))Fixtures.Add(x);foreach(var x in _db.GetNotifications(CurrentCareer.Id))Notifications.Add(x);foreach(var x in _db.GetCareerProgressSnapshots(CurrentCareer.Id))ProgressSnapshots.Add(x);RebuildSquadViews();if(SelectedCharacter is not null)SelectedCharacter=Characters.FirstOrDefault(x=>x.Id==SelectedCharacter.Id);foreach(var x in _db.GetEvents(CurrentCareer.Id))Events.Add(x);foreach(var x in _db.GetNews(CurrentCareer.Id))News.Add(x);foreach(var x in _db.GetSocial(CurrentCareer.Id))Social.Add(x);var matches=_db.GetMatches(CurrentCareer.Id,500);foreach(var match in matches.Reverse())MatchHistory.Add(match);if(SelectedLoggedMatch is not null)SelectedLoggedMatch=MatchHistory.FirstOrDefault(x=>x.Id==SelectedLoggedMatch.Id);var recent=matches.LastOrDefault();RecentMatchSummary=recent is null?"No matches logged":$"{recent.Input.TeamScore}-{recent.Input.OpponentScore} vs {recent.Input.Opponent}";CurrentForm=matches.Count==0?"No form":string.Join("  ",matches.TakeLast(5).Select(m=>m.Result));foreach(var e in Events.Take(4))DashboardItems.Add($"{e.Type.Replace('_',' ')}: {e.Summary}");if(DashboardItems.Count==0)DashboardItems.Add("No activity yet. Log a match to bring the world alive.");DebugText=BuildDebug(matches);foreach(var name in new[]{nameof(RecentMatchSummary),nameof(CurrentForm),nameof(NextFixture),nameof(PlayerSummary),nameof(DebugText),nameof(SelectedCharacterSummary),nameof(SelectedRelationship),nameof(SelectedSquadRelationship),nameof(PreMatchOpponent),nameof(PreMatchMeta),nameof(PreMatchForm),nameof(PreMatchAvailability),nameof(PreMatchKeyPlayers),nameof(PreMatchIntel),nameof(PreMatchScouting),nameof(UnreadNotificationCount),nameof(NotificationBadge),nameof(NotificationNavLabel),nameof(LatestHeadline),nameof(LatestIncoming),nameof(ProgressSummary),nameof(SelectedMatchHistoryDetails),nameof(PlayerMindsetTitle),nameof(PlayerMindsetSummary),nameof(PlayerMindsetDetail),nameof(RecoveryChoiceVisibility)})OnChanged(name);NotifyFifaState();}
    private void NotifyImmersionState(){OnChanged(nameof(ManagerName));OnChanged(nameof(ManagerRelationship));OnChanged(nameof(ManagerBriefing));OnChanged(nameof(AgentName));}
    public string OpenSelectedNotification(){var item=SelectedNotification??throw new InvalidOperationException("Select a world update first.");_db.MarkNotificationRead(item.Id);var action=item.Action;if(action.StartsWith("Messages:",StringComparison.OrdinalIgnoreCase)&&long.TryParse(action.AsSpan("Messages:".Length),out var characterId)){SelectedCharacter=Characters.FirstOrDefault(x=>x.Id==characterId);action="Messages";}Refresh();return action;}
    public void MarkAllNotificationsRead(){if(CurrentCareer is null)return;_db.MarkAllNotificationsRead(CurrentCareer.Id);Refresh();Status="World updates marked as read";}
    public void ClearReadNotifications(){if(CurrentCareer is null)return;var removed=_db.ClearReadNotifications(CurrentCareer.Id);SelectedNotification=null;Refresh();Status=removed==1?"Cleared 1 read update":$"Cleared {removed} read updates";}
    private string BuildDebug(IReadOnlyList<CareerMatch> matches){if(CurrentCareer is null)return"No active career.";var sb=new StringBuilder();sb.AppendLine("RAW CAREER STATE").AppendLine(JsonSerializer.Serialize(CurrentCareer,new JsonSerializerOptions{WriteIndented=true})).AppendLine().AppendLine($"MATCHES: {matches.Count}  CHARACTERS: {Characters.Count}  EVENTS: {Events.Count}").AppendLine("\nRECENT EVENT IMPORTANCE / CLASSIFICATION");foreach(var e in Events.Take(20))sb.AppendLine($"{e.Importance,3} {e.Type,-24} {e.Classification} | {e.Summary}");sb.AppendLine("\nREACTION RULES: event >=25; news >=48; social >=55; press >=62; character relevance >=72.");if(SelectedCharacter is not null){var ranked=new CareerCompanion.Core.Simulation.MemoryRanker().Rank(_db.GetMemories(SelectedCharacter.Id),"recent match",DateTime.UtcNow);sb.AppendLine($"\nRETRIEVED MEMORIES FOR {SelectedCharacter.Name.ToUpperInvariant()}");foreach(var m in ranked)sb.AppendLine($"{m.Importance,3} {m.Topic}: {m.Text}");}return sb.ToString();}
}
