using CareerCompanion.Core.LLM;
using CareerCompanion.Core.Domain;
using System.Net;
using System.Text;
using System.Text.Json;

namespace CareerCompanion.Tests;

public sealed class LlmTests
{
    private sealed class Handler(Func<HttpRequestMessage,CancellationToken,Task<HttpResponseMessage>> send):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)=>send(request,cancellationToken);}
    private static LlmRequest Request=>new("system","user","test-model");
    [Fact] public async Task Parses_successful_structured_response(){var data=JsonSerializer.Serialize(new{dialogue="Well played.",mood="pleased",relationshipDelta=2,trustDelta=1,respectDelta=1,newMemories=new[]{"A good exchange"}});var response=JsonSerializer.Serialize(new{output=new[]{new{content=new[]{new{text=data}}}},usage=new{input_tokens=20,output_tokens=12}});var provider=new OpenAIProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),()=>"fake");var result=await provider.GenerateAsync(Request);Assert.Equal("Well played.",result.Text);Assert.Equal(32,result.InputTokens+result.OutputTokens);}
    [Fact] public async Task Reports_rate_limit(){var provider=new OpenAIProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage((HttpStatusCode)429){Content=new StringContent("{}") }))),()=>"fake");await Assert.ThrowsAsync<LlmRateLimitException>(()=>provider.GenerateAsync(Request));}
    [Fact] public async Task Rejects_malformed_output(){var provider=new OpenAIProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("{\"output\":[]}")}))),()=>"fake");await Assert.ThrowsAsync<LlmUnavailableException>(()=>provider.GenerateAsync(Request));}
    [Fact] public async Task Reports_timeout(){var provider=new OpenAIProvider(new HttpClient(new Handler((_,ct)=>Task.FromCanceled<HttpResponseMessage>(ct))),()=>"fake");using var cts=new CancellationTokenSource();cts.Cancel();await Assert.ThrowsAsync<LlmUnavailableException>(()=>provider.GenerateAsync(Request,cts.Token));}
    [Fact] public async Task Missing_key_is_non_destructive_error(){var provider=new OpenAIProvider(new HttpClient(),()=>null);await Assert.ThrowsAsync<LlmUnavailableException>(()=>provider.GenerateAsync(Request));}
    [Fact] public async Task Parses_openai_compatible_chat_response(){var data=JsonSerializer.Serialize(new{dialogue="Keep your head up.",mood="supportive",relationshipDelta=1,trustDelta=1,respectDelta=0,newMemories=new[]{"A supportive exchange"}});var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{content=data}}},usage=new{prompt_tokens=3,completion_tokens=4}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");var result=await provider.GenerateAsync(Request with{Model="compatible:test-model"});Assert.Equal("Keep your head up.",result.Text);Assert.Equal(7,result.InputTokens+result.OutputTokens);}
    [Fact] public async Task Compatible_provider_never_exposes_reasoning_as_dialogue(){var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{reasoning="Relationship: score 0. Return only valid JSON."}}}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");await Assert.ThrowsAsync<LlmUnavailableException>(()=>provider.GenerateAsync(Request with{Model="compatible:test-model"}));}
    [Fact] public async Task Compatible_provider_rejects_plain_prompt_echoes(){var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{content="Relationship: score 0, trust 0. Relevant memories: none. User: hello"}}}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");await Assert.ThrowsAsync<LlmUnavailableException>(()=>provider.GenerateAsync(Request with{Model="compatible:test-model"}));}
    [Fact] public async Task Compatible_provider_accepts_plain_dialogue_when_json_is_ignored(){var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{content="Yeah, mate. I am here. What is up?"}}},usage=new{prompt_tokens=3,completion_tokens=8}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");var result=await provider.GenerateAsync(Request with{Model="compatible:test-model"});Assert.Equal("Yeah, mate. I am here. What is up?",result.Text);Assert.Equal(11,result.InputTokens+result.OutputTokens);}
    [Fact] public async Task Compatible_provider_salvages_dialogue_from_broken_wrapper(){var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{content="{\"dialogue\":\"Keep pushing, mate.\",\"mood\":\"focused\","}}}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");var result=await provider.GenerateAsync(Request with{Model="compatible:test-model"});Assert.Equal("Keep pushing, mate.",result.Text);}
    // Reasoning models put a reasoning or thinking item ahead of the answer. Reading only the first item
    // threw away a perfectly good reply and reported it as malformed output.
    [Fact] public async Task Openai_provider_reads_past_a_reasoning_item(){var data=JsonSerializer.Serialize(new{dialogue="Train well and we will talk Friday.",mood="steady",relationshipDelta=0,trustDelta=0,respectDelta=0,newMemories=Array.Empty<string>()});var response=JsonSerializer.Serialize(new{output=new object[]{new{type="reasoning",summary=Array.Empty<string>()},new{type="message",content=new[]{new{type="output_text",text=data}}}}});var provider=new OpenAIProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),()=>"fake");var result=await provider.GenerateAsync(Request);Assert.Equal("Train well and we will talk Friday.",result.Text);}
    [Fact] public async Task Claude_provider_reads_past_a_thinking_block(){var data=JsonSerializer.Serialize(new{dialogue="Head up. Next one is yours.",mood="supportive",relationshipDelta=1,trustDelta=0,respectDelta=0,newMemories=Array.Empty<string>()});var response=JsonSerializer.Serialize(new{content=new object[]{new{type="thinking",thinking="considering the tone"},new{type="text",text=data}},usage=new{input_tokens=5,output_tokens=6}});var provider=new ClaudeProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),()=>"fake");var result=await provider.GenerateAsync(Request);Assert.Equal("Head up. Next one is yours.",result.Text);Assert.Equal(11,result.InputTokens+result.OutputTokens);}
    [Fact] public async Task Claude_provider_keeps_plain_dialogue_when_the_json_wrapper_is_ignored(){var response=JsonSerializer.Serialize(new{content=new[]{new{type="text",text="Fair effort today. Rest up."}},usage=new{input_tokens=4,output_tokens=4}});var provider=new ClaudeProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),()=>"fake");var result=await provider.GenerateAsync(Request);Assert.Equal("Fair effort today. Rest up.",result.Text);}
    [Fact] public async Task Openai_provider_salvages_a_truncated_wrapper(){var response=JsonSerializer.Serialize(new{output=new object[]{new{type="message",content=new[]{new{type="output_text",text="{\"dialogue\":\"We go again Saturday.\",\"mood\":"}}}}});var provider=new OpenAIProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),()=>"fake");var result=await provider.GenerateAsync(Request);Assert.Equal("We go again Saturday.",result.Text);}
    [Fact] public async Task Deltas_outside_the_allowed_range_are_clamped_rather_than_rejected(){var data=JsonSerializer.Serialize(new{dialogue="That meant a lot to me.",mood="proud",relationshipDelta=40,trustDelta="2",respectDelta=0,newMemories="A shared moment"});var response=JsonSerializer.Serialize(new{choices=new[]{new{message=new{content=data}}}});var provider=new OpenAICompatibleProvider(new HttpClient(new Handler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(response,Encoding.UTF8,"application/json")}))),"http://localhost:1234/v1",()=>"test");var result=await provider.GenerateAsync(Request with{Model="compatible:test-model"});Assert.Equal(5,result.RelationshipDelta);Assert.Equal(2,result.TrustDelta);Assert.Single(result.Memories);}
    [Fact] public void Stored_prompt_echoes_are_hidden_from_the_message_view(){var message=new ConversationMessage("assistant","{\"dialogue\":\"Relationship: score 0, trust 0.\"}",DateTime.UtcNow);Assert.Contains("previous reply could not",message.DisplayContent,StringComparison.OrdinalIgnoreCase);}
}
