using CareerCompanion.Core.Domain;
using CareerCompanion.Core.Persistence;

namespace CareerCompanion.Tests;

public sealed class PersistenceTests : IDisposable
{
    private readonly string _dir=Path.Combine(Path.GetTempPath(),"touchline-tests-"+Guid.NewGuid().ToString("N"));private string DbPath=>Path.Combine(_dir,"world.db");
    private Database NewDb(){var db=new Database(DbPath);db.Migrate();return db;}
    [Fact] public void Career_survives_restart(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8);var reopened=NewDb();Assert.Equal("Player",reopened.GetCareer(id).PlayerName);}
    [Fact] public void Linked_career_preserves_provider_date(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8,"2017-08-27");Assert.Equal("2017-08-27",db.GetCareer(id).CurrentDate);}
    [Fact] public void Provider_update_preserves_career_date(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8);db.UpdateCareerFromProvider(id,"Player","English",18,"Club","League","2017/18","2017-08-27","CM",8);Assert.Equal("2017-08-27",db.GetCareer(id).CurrentDate);}
    [Fact] public void Conversations_survive_restart(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var ch=db.AddCharacter(career,"Mate",22,"","Club","ST","Starter",CharacterType.Teammate);var conversation=db.StartConversation(career,ch,SceneType.PrivateMessage);db.AddMessage(conversation,"user","Good match");db.AddMessage(conversation,"assistant","Cheers.");Assert.Equal(2,NewDb().GetMessages(career,ch).Count);}
    [Fact] public void Match_event_and_backup_are_consistent(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var match=db.SaveMatch(career,new("2017-01-01","League","Other",true,2,0,true,90,1,0,8,false,false,false,false,""));db.SaveEvent(new(0,career,match,"MATCH_WON",DateTime.UtcNow,30,"[]","{}","Won"));var backup=Path.Combine(_dir,"backup.db");db.Backup(backup);var restored=new Database(backup);Assert.Single(restored.GetMatches(career));Assert.Single(restored.GetEvents(career));}
    [Fact] public void Match_review_survives_restart_and_dismissal_is_sticky(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);db.StageMatchReview(career,"FIFA 18 Save","event-1","Career1","abc",DateTime.UtcNow,"{\"score\":1}","{\"snapshot\":1}");var reopened=NewDb();var review=Assert.Single(reopened.GetMatchReviews(career,"Pending"));reopened.SetMatchReviewStatus(review.Id,"Dismissed");reopened.StageMatchReview(career,"FIFA 18 Save","event-1","Career2","def",DateTime.UtcNow,"{\"score\":2}","{\"snapshot\":2}");Assert.Empty(reopened.GetMatchReviews(career,"Pending"));Assert.Equal("Dismissed",reopened.GetMatchReviewStatus(career,"FIFA 18 Save","event-1"));}
    [Fact] public void Match_limit_returns_latest_rows_in_chronological_order(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);for(var i=1;i<=105;i++)db.SaveMatch(career,new($"2017-01-{Math.Min(28,i):00}","League",$"Opponent {i}",true,i,0,true,90,0,0,7,false,false,false,false,""));var latest=db.GetMatches(career,5);Assert.Equal("Opponent 101",latest[0].Input.Opponent);Assert.Equal("Opponent 105",latest[^1].Input.Opponent);Assert.Equal(latest[^1],db.GetMatch(career,latest[^1].Id));}
    [Fact] public void Match_preserves_unknown_starter_status(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var id=db.SaveMatch(career,new("2017-01-01","League","Opponent",true,1,0,true,90,0,0,7,false,false,false,false,"",StartedKnown:false));Assert.False(db.GetMatch(career,id).Input.StartedKnown);}
    [Fact] public void Migration_adds_starter_evidence_column_to_existing_database(){Directory.CreateDirectory(_dir);var db=new Database(DbPath);using(var connection=db.Open()){using var cmd=connection.CreateCommand();cmd.CommandText="CREATE TABLE matches(id INTEGER PRIMARY KEY,career_id INTEGER NOT NULL,date TEXT NOT NULL,competition TEXT NOT NULL,opponent TEXT NOT NULL,is_home INTEGER NOT NULL,team_score INTEGER NOT NULL,opponent_score INTEGER NOT NULL,started INTEGER NOT NULL,minutes INTEGER NOT NULL,goals INTEGER NOT NULL,assists INTEGER NOT NULL,rating REAL NOT NULL,yellow_card INTEGER NOT NULL,red_card INTEGER NOT NULL,penalty_scored INTEGER NOT NULL,penalty_missed INTEGER NOT NULL,notes TEXT NOT NULL,next_opponent TEXT,is_derby INTEGER NOT NULL,is_major INTEGER NOT NULL,result TEXT NOT NULL,created_at TEXT NOT NULL)";cmd.ExecuteNonQuery();}db.Migrate();using var reopened=db.Open();using var info=reopened.CreateCommand();info.CommandText="PRAGMA table_info(matches)";using var reader=info.ExecuteReader();var columns=new List<string>();while(reader.Read())columns.Add(reader.GetString(1));Assert.Contains("started_known",columns);}
    [Fact] public void Notifications_and_progress_are_deduplicated_and_persisted(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","League","2017/18","CM",8);db.AddNotification(career,"Message","Mate","Good match","Messages",50,"same");db.AddNotification(career,"Message","Mate","Duplicate","Messages",50,"same");Assert.Single(NewDb().GetNotifications(career));var snapshot=new CareerProgressSnapshot(0,career,DateTime.UtcNow,"2017-01-02","Club","League","CM",8,75,3,false,1,0,0,0,0,"fingerprint");Assert.True(db.AddCareerProgressSnapshot(snapshot));Assert.False(db.AddCareerProgressSnapshot(snapshot));Assert.Equal(75,NewDb().GetLatestCareerProgressSnapshot(career)!.Overall);}
    public void Dispose(){try{Directory.Delete(_dir,true);}catch{}}
}
