using CareerCompanion.Core.Domain;
using CareerCompanion.Core.Persistence;

namespace CareerCompanion.Tests;

public sealed class PersistenceTests : IDisposable
{
    private readonly string _dir=Path.Combine(Path.GetTempPath(),"touchline-tests-"+Guid.NewGuid().ToString("N"));private string DbPath=>Path.Combine(_dir,"world.db");
    private Database NewDb(){var db=new Database(DbPath);db.Migrate();return db;}
    [Fact] public void Career_survives_restart(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8);var reopened=NewDb();Assert.Equal("Player",reopened.GetCareer(id).PlayerName);}
    [Fact] public void Linked_career_preserves_provider_date(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8,"2017-08-27");Assert.Equal("2017-08-27",db.GetCareer(id).CurrentDate);}
    [Fact] public void Provider_update_preserves_career_date(){var db=NewDb();var id=db.CreateCareer("Save","Player","English",18,"Club","League","2017/18","CM",8);db.UpdateCareerFromProvider(id,"Player","English",18,"Club","League","2017/18","2017-08-27","CM",8);Assert.Equal("2017-08-27",db.GetCareer(id).CurrentDate);}
    [Fact] public void Conversations_survive_restart_with_context(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var ch=db.AddCharacter(career,"Mate",22,"","Club","ST","Starter",CharacterType.Teammate);var conversation=db.StartConversation(career,ch,SceneType.PrivateMessage,"{}",new DateTime(2017,9,2));db.AddMessage(conversation,"user","Good match",new DateTime(2017,9,2,18,0,0));db.AddMessage(conversation,"assistant","Cheers.",new DateTime(2017,9,2,18,1,0));var messages=NewDb().GetMessages(career,ch);Assert.Equal(2,messages.Count);Assert.Equal("Private message | 02 Sep 2017 00:00",messages[1].ConversationContext);Assert.Equal("Replying to: Good match",messages[1].ReplyContext);Assert.Equal("02 Sep 2017 18:01",messages[1].DisplayTimestamp);}
    [Fact] public void Match_event_and_backup_are_consistent(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var match=db.SaveMatch(career,new("2017-01-01","League","Other",true,2,0,true,90,1,0,8,false,false,false,false,""));db.SaveEvent(new(0,career,match,"MATCH_WON",DateTime.UtcNow,30,"[]","{}","Won"));var backup=Path.Combine(_dir,"backup.db");db.Backup(backup);var restored=new Database(backup);Assert.Single(restored.GetMatches(career));Assert.Single(restored.GetEvents(career));}
    [Fact] public void Match_review_survives_restart_and_dismissal_is_sticky(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);db.StageMatchReview(career,"FIFA 18 Save","event-1","Career1","abc",DateTime.UtcNow,"{\"score\":1}","{\"snapshot\":1}");var reopened=NewDb();var review=Assert.Single(reopened.GetMatchReviews(career,"Pending"));reopened.SetMatchReviewStatus(review.Id,"Dismissed");reopened.StageMatchReview(career,"FIFA 18 Save","event-1","Career2","def",DateTime.UtcNow,"{\"score\":2}","{\"snapshot\":2}");Assert.Empty(reopened.GetMatchReviews(career,"Pending"));Assert.Equal("Dismissed",reopened.GetMatchReviewStatus(career,"FIFA 18 Save","event-1"));}
    [Fact] public void Match_limit_returns_latest_rows_in_chronological_order(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);for(var i=1;i<=105;i++)db.SaveMatch(career,new($"2017-01-{Math.Min(28,i):00}","League",$"Opponent {i}",true,i,0,true,90,0,0,7,false,false,false,false,""));var latest=db.GetMatches(career,5);Assert.Equal("Opponent 101",latest[0].Input.Opponent);Assert.Equal("Opponent 105",latest[^1].Input.Opponent);Assert.Equal(latest[^1],db.GetMatch(career,latest[^1].Id));}
    [Fact] public void Match_preserves_unknown_starter_status(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","CM",8);var id=db.SaveMatch(career,new("2017-01-01","League","Opponent",true,1,0,true,90,0,0,7,false,false,false,false,"",StartedKnown:false));Assert.False(db.GetMatch(career,id).Input.StartedKnown);}
    [Fact] public void Match_and_fixture_preserve_international_context(){var db=NewDb();var career=db.CreateCareer("Save","Player","Portugal",18,"Club","","2017/18","ST",9);var id=db.SaveMatch(career,new("2017-09-01","FIFA WC Qualifiers","England",true,2,1,true,90,1,0,8,false,false,false,false,"",TeamContext:"International",RepresentingTeam:"Portugal"));var match=db.GetMatch(career,id);Assert.Equal("International",match.Input.TeamContext);Assert.Equal("Portugal",match.Input.RepresentingTeam);db.UpsertFixture(career,"FIFA 18 Save","national-fixture","2017-09-05","FIFA WC Qualifiers","France",true,80,"news","hash","International","Portugal");var fixture=Assert.Single(db.GetFixtures(career));Assert.Equal("International",fixture.TeamContext);Assert.Equal("Portugal",fixture.RepresentingTeam);}
    [Fact] public void Opening_message_sender_marks_only_that_senders_alerts_read(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","","2017/18","ST",9);db.AddNotification(career,"Message","Mate","One","Messages:11",60,"m1");db.AddNotification(career,"Message","Mate","Two","Messages:11",60,"m2");db.AddNotification(career,"Manager","Boss","Three","Messages:12",60,"m3");db.MarkMessageNotificationsRead(career,11);var notices=db.GetNotifications(career);Assert.All(notices.Where(x=>x.Action=="Messages:11"),x=>Assert.True(x.IsRead));Assert.True(notices.Single(x=>x.Action=="Messages:12").IsRead==false);}
    [Fact] public void Record_breakthrough_creates_special_event_and_message(){var db=NewDb();var career=db.CreateCareer("Save","Player","",20,"Club","UEFA Champions League","2017/18","ST",9,"2017-09-01");var agent=db.AddCharacter(career,"Agent",40,"","","Agent","Representative",CharacterType.Agent);var service=new CareerCompanion.Core.Services.CareerService(db);var prior=service.ProcessMatch(career,new("2017-09-01","UEFA Champions League","A",true,1,0,true,90,17,0,8,false,false,false,false,""));var result=service.ProcessMatch(career,new("2017-09-02","UEFA Champions League","B",true,1,0,true,90,1,0,8,false,false,false,false,""));Assert.Contains(result.Events,x=>x.Type=="FOOTBALL_RECORD_BROKEN");var world=new CareerCompanion.Core.Services.AutomaticWorldService(db).ApplyMatch(result,true,true,false,false,false);Assert.Contains(db.GetNotifications(career),x=>x.Kind=="Record");Assert.NotEmpty(db.GetMessages(career,agent));}
    [Fact] public void Migration_adds_starter_evidence_column_to_existing_database(){Directory.CreateDirectory(_dir);var db=new Database(DbPath);using(var connection=db.Open()){using var cmd=connection.CreateCommand();cmd.CommandText="CREATE TABLE matches(id INTEGER PRIMARY KEY,career_id INTEGER NOT NULL,date TEXT NOT NULL,competition TEXT NOT NULL,opponent TEXT NOT NULL,is_home INTEGER NOT NULL,team_score INTEGER NOT NULL,opponent_score INTEGER NOT NULL,started INTEGER NOT NULL,minutes INTEGER NOT NULL,goals INTEGER NOT NULL,assists INTEGER NOT NULL,rating REAL NOT NULL,yellow_card INTEGER NOT NULL,red_card INTEGER NOT NULL,penalty_scored INTEGER NOT NULL,penalty_missed INTEGER NOT NULL,notes TEXT NOT NULL,next_opponent TEXT,is_derby INTEGER NOT NULL,is_major INTEGER NOT NULL,result TEXT NOT NULL,created_at TEXT NOT NULL)";cmd.ExecuteNonQuery();}db.Migrate();using var reopened=db.Open();using var info=reopened.CreateCommand();info.CommandText="PRAGMA table_info(matches)";using var reader=info.ExecuteReader();var columns=new List<string>();while(reader.Read())columns.Add(reader.GetString(1));Assert.Contains("started_known",columns);}
    [Fact] public void Notifications_and_progress_are_deduplicated_and_persisted(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","League","2017/18","CM",8);db.AddNotification(career,"Message","Mate","Good match","Messages",50,"same");db.AddNotification(career,"Message","Mate","Duplicate","Messages",50,"same");Assert.Single(NewDb().GetNotifications(career));var snapshot=new CareerProgressSnapshot(0,career,DateTime.UtcNow,"2017-01-02","Club","League","CM",8,75,3,false,1,0,0,0,0,"fingerprint");Assert.True(db.AddCareerProgressSnapshot(snapshot));Assert.False(db.AddCareerProgressSnapshot(snapshot));Assert.Equal(75,NewDb().GetLatestCareerProgressSnapshot(career)!.Overall);}
    [Fact] public void Manual_match_delete_removes_generated_world_but_provider_match_is_protected(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","League","2017/18","CM",8);var manual=db.SaveMatch(career,new("2017-01-01","League","Manual",true,2,0,true,90,1,0,8,false,false,false,false,""));var evt=db.SaveEvent(new(0,career,manual,"PLAYER_SCORED",new DateTime(2017,1,1),40,"[]","{}","Scored"));db.AddNews(career,evt,"Outlet","Headline","Body","positive",40);db.DeleteManualMatch(career,manual);Assert.Empty(db.GetMatches(career));Assert.Empty(db.GetEvents(career));Assert.Empty(db.GetNews(career));var linked=db.SaveProviderMatch(career,"FIFA 18 Save","event",new("2017-01-02","League","FIFA",true,1,0,true,90,0,0,7,false,false,false,false,"")).MatchId;Assert.Throws<InvalidOperationException>(()=>db.DeleteManualMatch(career,linked));}
    [Fact] public void Match_correction_updates_facts_and_rebuilds_events(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","League","2017/18","ST",9);var service=new CareerCompanion.Core.Services.CareerService(db);var original=service.ProcessMatch(career,new("2017-01-01","League","Other",true,1,0,true,90,1,0,7,false,false,false,false,""));var corrected=service.UpdateMatch(career,original.Match.Id,original.Match.Input with{Goals=3,Rating=9.5});Assert.Equal(3,corrected.Match.Input.Goals);Assert.Contains(corrected.Events,x=>x.Type=="PLAYER_HATTRICK");Assert.DoesNotContain(db.GetEvents(career),x=>x.Type=="PLAYER_SCORED");}
    [Fact] public void Player_psychology_survives_restart(){var db=NewDb();var career=db.CreateCareer("Save","Player","",18,"Club","League","2017/18","ST",9);db.SavePlayerState(new(career,"under intense pressure",24,78,60,44,52,"Final defeat",true,new DateTime(2017,5,20)));var state=NewDb().GetPlayerState(career);Assert.Equal("under intense pressure",state.Mood);Assert.Equal(78,state.Pressure);Assert.True(state.NeedsSupport);}
    public void Dispose(){try{Directory.Delete(_dir,true);}catch{}}
}
